CLANDRO_PKG_HOMEPAGE=https://www.ladspa.org/
CLANDRO_PKG_DESCRIPTION="Linux Audio Developer's Simple Plugin API"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.17
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://www.ladspa.org/download/ladspa_sdk_${CLANDRO_PKG_VERSION}.tgz
CLANDRO_PKG_SHA256=27d24f279e4b81bd17ecbdcc38e4c42991bb388826c0b200067ce0eb59d3da5b
CLANDRO_PKG_DEPENDS="libc++, libsndfile"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="targets"

clandro_step_pre_configure() {
	CLANDRO_PKG_SRCDIR+="/src"
	CLANDRO_PKG_BUILDDIR="$CLANDRO_PKG_SRCDIR"
}
