CLANDRO_PKG_HOMEPAGE=https://www.gnupg.org/related_software/gpgme/
CLANDRO_PKG_DESCRIPTION="C++ bindings for GPGME"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.0.0"
CLANDRO_PKG_SRCURL="https://www.gnupg.org/ftp/gcrypt/gpgmepp/gpgmepp-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=d4796049c06708a26f3096f748ef095347e1a3c1e570561701fe952c3f565382
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="gpgme, libc++, libgpg-error"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
"
