# Contributor: @Neo-Oli
CLANDRO_PKG_HOMEPAGE=https://github.com/xorg62/tty-clock
CLANDRO_PKG_DESCRIPTION="Simple terminal clock"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_VERSION=2.3
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_MAINTAINER="Oliver Schmidhauser @Neo-Oli"
CLANDRO_PKG_SRCURL=https://github.com/xorg62/tty-clock/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=343e119858db7d5622a545e15a3bbfde65c107440700b62f9df0926db8f57984
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="ncurses"
CLANDRO_PKG_BUILD_IN_SRC=true
