CLANDRO_PKG_HOMEPAGE=https://znc.in/
CLANDRO_PKG_DESCRIPTION="An advanced IRC bouncer"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.10.2"
CLANDRO_PKG_SRCURL=https://znc.in/releases/archive/znc-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=5b7561f3b100234d58ae4946eac0262ab305d275c094e64ae723e45d07be08ab
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
CLANDRO_PKG_DEPENDS="libc++, libicu, libsasl, openssl, zlib"
CLANDRO_PKG_FORCE_CMAKE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DWANT_I18N=OFF
"
