CLANDRO_PKG_HOMEPAGE=https://github.com/libpinyin/ibus-libpinyin
CLANDRO_PKG_DESCRIPTION="Intelligent Pinyin engine based on libpinyin for IBus"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.16.5
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/libpinyin/ibus-libpinyin/releases/download/$CLANDRO_PKG_VERSION/ibus-libpinyin-$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=cc652d48e68b8b03afc5e9e08509676aee89f9d492b9a3897cd028bcc800ce31
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_DEPENDS="ibus, libpinyin, libopencc, libsqlite, lua51, libdb"
