CLANDRO_PKG_HOMEPAGE=https://www.gnu.org/software/bc/
CLANDRO_PKG_DESCRIPTION="Arbitrary precision numeric processing language"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.08.2"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://mirrors.kernel.org/gnu/bc/bc-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=ae470fec429775653e042015edc928d07c8c3b2fc59765172a330d3d87785f86
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="readline,flex"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
--infodir=$CLANDRO_PREFIX/share/info
--mandir=$CLANDRO_PREFIX/share/man
--with-readline
"
