CLANDRO_PKG_HOMEPAGE=https://tsl0922.github.io/ttyd/
CLANDRO_PKG_DESCRIPTION="Command-line tool for sharing terminal over the web"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.7.7"
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/tsl0922/ttyd/archive/refs/tags/$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=039dd995229377caee919898b7bd54484accec3bba49c118e2d5cd6ec51e3650
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="json-c, libcap, libuv, libwebsockets, openssl, zlib"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DCMAKE_XXD=$CLANDRO_PKG_TMPDIR/xxd"
