CLANDRO_SUBPKG_INCLUDE="lib/xorg/protocol.txt"
CLANDRO_SUBPKG_DESCRIPTION="X.Org protocol.txt file"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_REPLACES="xorg-server-xvfb (<< 1.20.11-8)"
CLANDRO_SUBPKG_BREAKS="xorg-server-xvfb (<< 1.20.11-8)"
