CLANDRO_PKG_HOMEPAGE=https://github.com/holman/spark
CLANDRO_PKG_DESCRIPTION="▁▂▃▅▂▇ in your shell"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.0.1
CLANDRO_PKG_SRCURL=$CLANDRO_PKG_HOMEPAGE/archive/v$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=a81c1bc538ce8e011f62264fe6f33d28042ff431b510a6359040dc77403ebab6
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_DEPENDS=bash
CLANDRO_PKG_PLATFORM_INDEPENDENT=true

clandro_step_make_install() {
	local bin="$(basename $CLANDRO_PKG_HOMEPAGE)"
	install -D "$bin" -t "$CLANDRO_PREFIX/bin"
}
