CLANDRO_PKG_HOMEPAGE=https://github.com/KhronosGroup/SPIRV-Tools
CLANDRO_PKG_DESCRIPTION="SPIR-V Tools"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.4.341.0"
CLANDRO_PKG_SRCURL="https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/vulkan-sdk-${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=15bfb678138cdf9cd1480dfb952547bbb66b763a735b6d5582578572f5c2e6f9
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BUILD_DEPENDS="spirv-headers (=${CLANDRO_PKG_VERSION})"
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="vulkan-sdk-\d+\.\d+\.\d+\.\d+"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
-DSPIRV-Headers_SOURCE_DIR=${CLANDRO_PREFIX}
-DSPIRV_WERROR=OFF
"
