CLANDRO_PKG_HOMEPAGE=https://unqlite.org/
CLANDRO_PKG_DESCRIPTION="Transactional embedded database engine"
CLANDRO_PKG_LICENSE="BSD 2-Clause, Sleepycat"
CLANDRO_PKG_LICENSE_FILE="LICENSE, src/jx9_license.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.1.9
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/symisc/unqlite/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=33d5b5e7b2ca223942e77d31112d2e20512bc507808414451c8a98a7be5e15c0
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
