CLANDRO_PKG_HOMEPAGE="https://invent.kde.org/frameworks/oxygen-icons"
CLANDRO_PKG_DESCRIPTION="The Oxygen Icon Theme"
CLANDRO_PKG_LICENSE="LGPL-2.1-or-later"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.1.0"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/oxygen-icons/oxygen-icons-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256="16ca971079c5067c4507cabf1b619dc87dd6b326fd5c2dd9f5d43810f2174d68"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BUILD_DEPENDS="extra-cmake-modules, qt6-qttools"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
"
