CLANDRO_PKG_HOMEPAGE=https://www.gnu.org/s/rcs
CLANDRO_PKG_DESCRIPTION="The GNU Revision Control System"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=5.10.1
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://mirrors.kernel.org/gnu/rcs/rcs-${CLANDRO_PKG_VERSION}.tar.lz
CLANDRO_PKG_SHA256=43ddfe10724a8b85e2468f6403b6000737186f01e60e0bd62fde69d842234cc5
CLANDRO_PKG_DEPENDS="diffutils"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
ac_cv_path_DIFF=$CLANDRO_PREFIX/bin/diff
ac_cv_path_DIFF3=$CLANDRO_PREFIX/bin/diff3
"
