CLANDRO_SUBPKG_DESCRIPTION="Platform-independent data for tvheadend"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_INCLUDE="share/tvheadend/"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_BREAKS="tvheadend (<< 4.2.8-9)"
CLANDRO_SUBPKG_REPLACES="tvheadend (<< 4.2.8-9)"
