CLANDRO_PKG_HOMEPAGE=https://github.com/ericniebler/range-v3
CLANDRO_PKG_DESCRIPTION="Range library for C++14/17/20, basis for C++20's std::ranges"
CLANDRO_PKG_LICENSE="BSL-1.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.12.0"
CLANDRO_PKG_SRCURL=https://github.com/ericniebler/range-v3/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=015adb2300a98edfceaf0725beec3337f542af4915cec4d0b89fa0886f4ba9cb
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DRANGE_V3_DOCS=OFF
-DRANGE_V3_EXAMPLES=OFF
-DRANGE_V3_HEADER_CHECKS=OFF
-DRANGE_V3_PERF=OFF
-DRANGE_V3_TESTS=OFF
"
