CLANDRO_SUBPKG_INCLUDE="share/help/"
CLANDRO_SUBPKG_DESCRIPTION="Gnumeric help files"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_BREAKS="gnumeric (<< 1.12.53)"
CLANDRO_SUBPKG_REPLACES="gnumeric (<< 1.12.53)"
