CLANDRO_PKG_HOMEPAGE=https://icculus.org/physfs/
CLANDRO_PKG_DESCRIPTION="A portable, flexible file i/o abstraction"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=3.2.0
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/icculus/physfs/archive/refs/tags/release-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=1991500eaeb8d5325e3a8361847ff3bf8e03ec89252b7915e1f25b3f8ab5d560
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DPHYSFS_BUILD_STATIC=OFF
-DPHYSFS_BUILD_TEST=OFF
"
