CLANDRO_SUBPKG_DESCRIPTION="Platform-independent data for lyx"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_INCLUDE="share/lyx/"
CLANDRO_SUBPKG_BREAKS="lyx (<< 2.3.7)"
CLANDRO_SUBPKG_REPLACES="lyx (<< 2.3.7)"
