CLANDRO_PKG_HOMEPAGE=https://icecast.org/
CLANDRO_PKG_DESCRIPTION="Library which can be used to write a source client like ices."
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=2.4.6
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://downloads.xiph.org/releases/libshout/libshout-$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=39cbd4f0efdfddc9755d88217e47f8f2d7108fa767f9d58a2ba26a16d8f7c910
CLANDRO_PKG_DEPENDS="libogg, libvorbis, libxml2, openssl"
CLANDRO_PKG_BUILD_IN_SRC=true
