CLANDRO_PKG_HOMEPAGE=https://github.com/mapbox/protozero
CLANDRO_PKG_DESCRIPTION="Minimalistic protocol buffer decoder and encoder in C++"
CLANDRO_PKG_LICENSE="BSD 2-Clause"
CLANDRO_PKG_LICENSE_FILE="LICENSE.md"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.8.0
CLANDRO_PKG_SRCURL=https://github.com/mapbox/protozero/archive/refs/tags/v${CLANDRO_PKG_VERSION}.zip
CLANDRO_PKG_SHA256=1f9616bbe55e8cd8dac93f37f0573a2e8eed5fb419632cd8057630f800f41c0b
CLANDRO_PKG_GROUPS="science"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DPYBIND11_FINDPYTHON=OFF"
