CLANDRO_PKG_HOMEPAGE=https://xorg.freedesktop.org/
CLANDRO_PKG_DESCRIPTION="X11 authorisation library"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.0.12"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXau-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=74d0e4dfa3d39ad8939e99bda37f5967aba528211076828464d2777d477fc0fb
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_DEPENDS="xorgproto"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
--disable-static
"
