CLANDRO_PKG_HOMEPAGE=http://xmlsoft.org/libxslt/
CLANDRO_PKG_DESCRIPTION="XSLT processing library"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.1.45"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://gitlab.gnome.org/GNOME/libxslt/-/archive/v${CLANDRO_PKG_VERSION}/libxslt-v${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=4298285dfe7220ddfc1908e97b0cf3a67134e6d2d0f1af17c38220eba57477ab
CLANDRO_PKG_DEPENDS="libgcrypt, libgpg-error, libxml2, libandroid-glob"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BREAKS="libxslt-dev"
CLANDRO_PKG_REPLACES="libxslt-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
-DLIBXSLT_WITH_PYTHON=no
"

clandro_step_pre_configure() {
	LDFLAGS+=" -landroid-glob"
}
