CLANDRO_SUBPKG_INCLUDE="share/help/"
CLANDRO_SUBPKG_DESCRIPTION="Evince help files"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_BREAKS="evince (<< 44.3)"
CLANDRO_SUBPKG_REPLACES="evince (<< 44.3)"
