CLANDRO_PKG_HOMEPAGE="http://www.qhull.org"
CLANDRO_PKG_DESCRIPTION="Calculate convex hulls and related structures"
CLANDRO_PKG_GROUPS="science"
CLANDRO_PKG_LICENSE="custom"
CLANDRO_PKG_LICENSE_FILE="COPYING.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=8.1-alpha3
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL="https://github.com/qhull/qhull/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=55b9d34f85fd42e16e5a851e48d27c9f4e0db65ba1028953f935a7318f184511
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
