CLANDRO_PKG_HOMEPAGE=http://www.fefe.de/libowfat/
CLANDRO_PKG_DESCRIPTION="GPL reimplementation of libdjb"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.33
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://www.fefe.de/libowfat/libowfat-$CLANDRO_PKG_VERSION.tar.xz
CLANDRO_PKG_SHA256=311ec8b3f4b72bb442e323fb013a98f956fa745547f2bc9456287b20d027cd7d
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="
prefix=$CLANDRO_PREFIX
LIBDIR=$CLANDRO_PREFIX/lib
MAN3DIR=$CLANDRO_PREFIX/share/man/man3
"
CLANDRO_PKG_MAKE_PROCESSES=1

clandro_step_pre_configure() {
	# Use pregenerated entities.h.
	cp $CLANDRO_PKG_BUILDER_DIR/entities.h $CLANDRO_PKG_BUILDDIR/
	touch -d "next hour" $CLANDRO_PKG_BUILDDIR/entities.h
}
