CLANDRO_PKG_HOMEPAGE=https://www.raylib.com/
CLANDRO_PKG_DESCRIPTION="A simple and easy-to-use library to enjoy videogames programming"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=5.5
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/raysan5/raylib/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=aea98ecf5bc5c5e0b789a76de0083a21a70457050ea4cc2aec7566935f5e258e
CLANDRO_PKG_DEPENDS="glfw"
CLANDRO_PKG_BUILD_DEPENDS="glu, opengl"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DPLATFORM=Desktop
-DBUILD_EXAMPLES=OFF
-DBUILD_SHARED_LIBS=ON
-DUSE_EXTERNAL_GLFW=ON
-DOPENGL_VERSION=2.1
"
