CLANDRO_PKG_HOMEPAGE='https://invent.kde.org/frameworks/kpty'
CLANDRO_PKG_DESCRIPTION='Pty abstraction'
CLANDRO_PKG_LICENSE="LGPL-2.0, LGPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.26.0"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/frameworks/${CLANDRO_PKG_VERSION%.*}/kpty-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=7613c26cfaa7465a2fe28a22762ceb38266414e7f4a94a127c09dc0628625553
CLANDRO_PKG_DEPENDS="kf6-kcoreaddons (>= ${CLANDRO_PKG_VERSION%.*}), kf6-ki18n (>= ${CLANDRO_PKG_VERSION%.*}), libc++, qt6-qtbase"
CLANDRO_PKG_BUILD_DEPENDS="extra-cmake-modules (>= ${CLANDRO_PKG_VERSION%.*}), qt6-qttools"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DCMAKE_DISABLE_FIND_PACKAGE_UTEMPTER=ON
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
