CLANDRO_PKG_HOMEPAGE=https://github.com/nemtrif/utfcpp
CLANDRO_PKG_DESCRIPTION="UTF8-CPP: UTF-8 with C++ in a Portable Way"
CLANDRO_PKG_LICENSE="BSD"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1:4.0.9"
CLANDRO_PKG_SRCURL=https://github.com/nemtrif/utfcpp/archive/refs/tags/v${CLANDRO_PKG_VERSION#*:}.tar.gz
CLANDRO_PKG_SHA256=397a9a2a6ed5238f854f490b0177b840abc6b62571ec3e07baa0bb94d3f14d5a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DUTF8CPP_ENABLE_TESTS=OFF
"
