CLANDRO_PKG_HOMEPAGE=https://www.blosc.org
CLANDRO_PKG_DESCRIPTION="A blocking, shuffling and loss-less compression library"
CLANDRO_PKG_LICENSE="BSD"
CLANDRO_PKG_LICENSE_FILE="\
LICENSES/BITSHUFFLE.txt
LICENSES/FASTLZ.txt
LICENSES/LZ4.txt
LICENSES/ZLIB.txt
LICENSES/ZSTD.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.0.2"
CLANDRO_PKG_SRCURL=https://github.com/Blosc/c-blosc2/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c711e988ec25c0e05030d4db996a2e07bad3d07000c62844a4f45b2a9860a6f1
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="liblz4, zlib, zstd"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_STATIC=OFF
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
-DDEACTIVATE_LZ4=OFF
-DDEACTIVATE_ZLIB=OFF
-DDEACTIVATE_ZSTD=OFF
-DPREFER_EXTERNAL_LZ4=ON
-DPREFER_EXTERNAL_ZLIB=ON
-DPREFER_EXTERNAL_ZSTD=ON
"
