CLANDRO_PKG_HOMEPAGE=https://github.com/pystardust/ytfzf
CLANDRO_PKG_DESCRIPTION="A POSIX script that helps you find Youtube videos (without API)"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.6.2"
CLANDRO_PKG_SRCURL=https://github.com/pystardust/ytfzf/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=73280e4ef4f490400a42bf582b713803c523587b0b30269859eaa6f2693ec9b1
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="curl, jq"
CLANDRO_PKG_RECOMMENDS="fzf, mpv"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"

clandro_step_make() {
	:
}
