CLANDRO_PKG_HOMEPAGE=https://github.com/Microsoft/GSL
CLANDRO_PKG_DESCRIPTION="Guidelines Support Library"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="4.2.1"
CLANDRO_PKG_SRCURL="https://github.com/microsoft/GSL/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=d959f1cb8bbb9c94f033ae5db60eaf5f416be1baa744493c32585adca066fe1f
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_DEPENDS="googletest"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DGSL_CXX_STANDARD=23
"
