CLANDRO_PKG_HOMEPAGE=https://xiph.org/vorbis/
CLANDRO_PKG_DESCRIPTION="Library for using the Ogg Vorbis compressed audio format"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.3.7
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=http://downloads.xiph.org/releases/vorbis/libvorbis-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b
CLANDRO_PKG_DEPENDS="libogg"
CLANDRO_PKG_BREAKS="libvorbis-dev"
CLANDRO_PKG_REPLACES="libvorbis-dev"
