CLANDRO_PKG_HOMEPAGE=https://ukoethe.github.io/vigra/
CLANDRO_PKG_DESCRIPTION="Computer vision library"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.12.4"
CLANDRO_PKG_SRCURL=https://github.com/ukoethe/vigra/archive/refs/tags/Version-${CLANDRO_PKG_VERSION//./-}.tar.gz
CLANDRO_PKG_SHA256=fa516eeb19f72ae98a6d5a284c033bc0e0070cb73a8c72985696d2ad73a9292a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_SED_REGEXP="s/-/./g"
CLANDRO_PKG_DEPENDS="imath, libc++, libhdf5, libjpeg-turbo, libpng, libtiff, openexr, zlib"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DRUN_RESULT=0
-DRUN_RESULT__TRYRUN_OUTPUT=201103
-DWITH_OPENEXR=ON
"
CLANDRO_PKG_RM_AFTER_INSTALL="doc"
