CLANDRO_PKG_HOMEPAGE=http://www.isthe.com/chongo/tech/comp/calc/
CLANDRO_PKG_DESCRIPTION="Arbitrary precision console calculator"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.16.1.2"
CLANDRO_PKG_SRCURL=https://github.com/lcn2/calc/releases/download/v$CLANDRO_PKG_VERSION/calc-$CLANDRO_PKG_VERSION.tar.bz2
CLANDRO_PKG_SHA256=6acf224ce446c22e262ceb192a051ef79fb121b882cd2c629955f184b30e9f51
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="ncurses, readline"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="LONG_BITS=$CLANDRO_ARCH_BITS"
CLANDRO_PKG_MAKE_PROCESSES=1
