CLANDRO_PKG_HOMEPAGE=https://www.opus-codec.org/
CLANDRO_PKG_DESCRIPTION="Utilities to encode and decode .opus files"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.2
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=https://downloads.xiph.org/releases/opus/opus-tools-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=b4e56cb00d3e509acfba9a9b627ffd8273b876b4e2408642259f6da28fa0ff86
CLANDRO_PKG_DEPENDS="libopusenc, libogg, libflac, opusfile, libopus"
