CLANDRO_PKG_HOMEPAGE=https://symas.com/lmdb/
CLANDRO_PKG_DESCRIPTION="LMDB implements a simplified variant of the BerkeleyDB (BDB) API"
CLANDRO_PKG_LICENSE="OpenLDAP"
CLANDRO_PKG_LICENSE_FILE="libraries/liblmdb/LICENSE"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.9.35"
CLANDRO_PKG_SRCURL="https://git.openldap.org/openldap/openldap/-/archive/LMDB_${CLANDRO_PKG_VERSION}/openldap-LMDB_${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=0d090c6a7c85a4f31a2ab0d734554c21097f24752393a190b0e51996b08f48c4
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="LMDB_\d+.\d+.\d+"
CLANDRO_PKG_UPDATE_VERSION_SED_REGEXP="s/LMDB_//"
CLANDRO_PKG_EXTRA_MAKE_ARGS="-C libraries/liblmdb"
CLANDRO_PKG_BUILD_IN_SRC=true

clandro_step_pre_configure() {
	CPPFLAGS+=" -DMDB_USE_ROBUST=0"
}
