CLANDRO_PKG_HOMEPAGE=https://panotools.sourceforge.net/
CLANDRO_PKG_DESCRIPTION="Part of the Panorama Tools by Helmut Dersch"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.9.23"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://downloads.sourceforge.net/panotools/libpano13-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=e7c076d37a14c39434962115e47ddbe18452ca3de5ce40e2aaefa7cf5815ea28
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libjpeg-turbo, libpng, libtiff, zlib"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
