CLANDRO_PKG_HOMEPAGE=https://github.com/DamirPorobic/kColorPicker
CLANDRO_PKG_DESCRIPTION="Qt based Color Picker with popup menu"
CLANDRO_PKG_LICENSE="LGPL-3.0-only"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.3.1"
CLANDRO_PKG_SRCURL="https://github.com/ksnip/kColorPicker/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=e78c785ec4a8a22a48a91835c97601f5704b5076b154415353b0d2697dc0b4f7
CLANDRO_PKG_DEPENDS="libc++, qt6-qtbase"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE=newest-tag
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DBUILD_SHARED_LIBS=ON
-DBUILD_WITH_QT6=ON
"
