CLANDRO_PKG_HOMEPAGE=https://xorg.freedesktop.org/
CLANDRO_PKG_DESCRIPTION="X server resource database utility"
CLANDRO_PKG_LICENSE="custom"
CLANDRO_PKG_LICENSE_FILE="COPYING"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.2.2
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://www.x.org/archive/individual/app/xrdb-$CLANDRO_PKG_VERSION.tar.xz
CLANDRO_PKG_SHA256=31f5fcab231b38f255b00b066cf7ea3b496df712c9eb2d0d50c670b63e5033f4
CLANDRO_PKG_DEPENDS="libx11, libxmu"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="--with-cpp=/usr/bin/cpp"
