CLANDRO_PKG_HOMEPAGE=https://github.com/KhronosGroup/OpenCL-CLHPP
CLANDRO_PKG_DESCRIPTION="Khronos OpenCL C++ Headers"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2025.07.22"
CLANDRO_PKG_SRCURL=https://github.com/KhronosGroup/OpenCL-CLHPP/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c1031afde6e9eb042e6fcfbc17078f4b437a7e8d55482a1ca6e0fa762d262a89
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_DEPENDS="opencl-headers"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTS=OFF
"
