CLANDRO_PKG_HOMEPAGE=https://github.com/agnostic-apollo/sudo
CLANDRO_PKG_DESCRIPTION="A wrapper script to drop to the supported shells or execute shell script files or their text passed as an argument as the root (superuser) user in the Termux app"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@agnostic-apollo"
CLANDRO_PKG_VERSION="1.2.0"
CLANDRO_PKG_SRCURL=https://github.com/agnostic-apollo/sudo/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=882d5af3963cfa8981dda65bc4ff1c90a706e0c4b0b14cd1fe4a605b1f087a0c
CLANDRO_PKG_DEPENDS="bash"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_CONFLICTS="tsu"
CLANDRO_PKG_REPLACES="tsu"
CLANDRO_PKG_EXTRA_MAKE_ARGS="SUDO_PKG__VERSION=${CLANDRO_PKG_VERSION} SUDO_PKG__ARCH=${CLANDRO_ARCH} \
CLANDRO__NAME=${CLANDRO__NAME} CLANDRO__LNAME=${CLANDRO__LNAME} \
CLANDRO_APP__NAME=${CLANDRO_APP__NAME} \
CLANDRO_APP__PACKAGE_NAME=${CLANDRO_APP__PACKAGE_NAME} CLANDRO_APP__DATA_DIR=${CLANDRO_APP__DATA_DIR} \
CLANDRO__ROOTFS=${CLANDRO__ROOTFS} CLANDRO__HOME=${CLANDRO__HOME} CLANDRO__PREFIX=${CLANDRO__PREFIX} \
CLANDRO_ENV__S_ROOT=${CLANDRO_ENV__S_ROOT} \
CLANDRO_ENV__SS_CLANDRO=${CLANDRO_ENV__SS_CLANDRO} CLANDRO_ENV__S_CLANDRO=${CLANDRO_ENV__S_CLANDRO} \
CLANDRO_ENV__SS_CLANDRO_APP=${CLANDRO_ENV__SS_CLANDRO_APP} CLANDRO_ENV__S_CLANDRO_APP=${CLANDRO_ENV__S_CLANDRO_APP}"

clandro_step_install_license() {
	mkdir -p "$CLANDRO_PREFIX/share/doc/$CLANDRO_PKG_NAME/licenses"
	cp -af "$CLANDRO_PKG_SRCDIR/LICENSE" "$CLANDRO_PREFIX/share/doc/$CLANDRO_PKG_NAME/copyright"
	cp -af "$CLANDRO_PKG_SRCDIR/licenses/"* "$CLANDRO_PREFIX/share/doc/$CLANDRO_PKG_NAME/licenses/"
}
