CLANDRO_PKG_HOMEPAGE=https://github.com/dvorka/mindforger
CLANDRO_PKG_DESCRIPTION="Thinking Notebook & Markdown Editor"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.0.0"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=git+https://github.com/dvorka/mindforger
CLANDRO_PKG_GIT_BRANCH=${CLANDRO_PKG_VERSION}
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="hunspell, libc++, qt5-qtbase, qt5-qtwebengine, zlib"
CLANDRO_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
PREFIX=$CLANDRO_PREFIX
CONFIG+=mfnocxx
CONFIG+=mfwebengine
"

clandro_step_pre_configure() {
	clandro_setup_ninja
	clandro_setup_cmake

	local OLD_TERMUX_PKG_SRCDIR="$CLANDRO_PKG_SRCDIR"
	local OLD_TERMUX_PKG_BUILDDIR="$CLANDRO_PKG_BUILDDIR"
	local OLD_TERMUX_PKG_EXTRA_CONFIGURE_ARGS="$CLANDRO_PKG_EXTRA_CONFIGURE_ARGS"

	CLANDRO_PKG_BUILDDIR="$CLANDRO_PKG_SRCDIR/deps/cmark-gfm/build"
	CLANDRO_PKG_SRCDIR=".."
	CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DCMARK_TESTS=OFF -DCMARK_SHARED=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5"

	mkdir -p "$CLANDRO_PKG_BUILDDIR"
	cd "$CLANDRO_PKG_BUILDDIR"
	clandro_step_configure_cmake
	cmake --build .

	CLANDRO_PKG_SRCDIR="$OLD_TERMUX_PKG_SRCDIR"
	CLANDRO_PKG_BUILDDIR="$OLD_TERMUX_PKG_BUILDDIR"
	CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="$OLD_TERMUX_PKG_EXTRA_CONFIGURE_ARGS"
}

clandro_step_configure() {
	"${CLANDRO_PREFIX}/opt/qt/cross/bin/qmake" \
		-spec "${CLANDRO_PREFIX}/lib/qt/mkspecs/termux-cross" \
		${CLANDRO_PKG_EXTRA_CONFIGURE_ARGS}
}
