CLANDRO_PKG_HOMEPAGE=https://github.com/theZiz/aha
CLANDRO_PKG_DESCRIPTION="Converts ANSI escape sequences of a unix terminal to HTML code"
CLANDRO_PKG_LICENSE="Mozilla-1.1, LGPL-2.0-or-later"
CLANDRO_PKG_LICENSE_FILE="LICENSE.MPL1.1, LICENSE.LGPLv2+"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.5.1
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/theZiz/aha/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=6aea13487f6b5c3e453a447a67345f8095282f5acd97344466816b05ebd0b3b1
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
