CLANDRO_PKG_HOMEPAGE="http://chipmunk2d.net"
CLANDRO_PKG_DESCRIPTION="A fast and lightweight 2D game physics library"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="7.0.3"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL="https://github.com/slembcke/Chipmunk2D/archive/refs/tags/Chipmunk-$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=1e6f093812d6130e45bdf4cb80280cb3c93d1e1833d8cf989d554d7963b7899a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_EXCLUDED_ARCHES="arm"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED=ON
-DBUILD_STATIC=OFF
"
