CLANDRO_PKG_HOMEPAGE=https://www.kokkonen.net/tjko/projects.html
CLANDRO_PKG_DESCRIPTION="JPEG optimizer that recompresses image files to a smaller size, without losing any information"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.5.6"
CLANDRO_PKG_SRCURL=https://github.com/tjko/jpegoptim/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=661a808dfffa933d78c6beb47a2937d572b9f03e94cbaaab3d4c0d72f410e9be
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libjpeg-turbo"
CLANDRO_PKG_BUILD_IN_SRC=true
