CLANDRO_PKG_HOMEPAGE=https://github.com/libsdl-org/SDL_image
CLANDRO_PKG_DESCRIPTION="A simple library to load images of various formats as SDL surfaces (version 3)"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_LICENSE_FILE="LICENSE.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.4.4"
CLANDRO_PKG_SRCURL="https://github.com/libsdl-org/SDL_image/releases/download/release-${CLANDRO_PKG_VERSION}/SDL3_image-${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=29751304a13d25ac513f24305fa25b06a6edd9607718c90129b8350d35fc5573
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libavif, libjpeg-turbo, libjxl, libpng, libtiff, libwebp, sdl3"

# disable shared aka for dynamic linking
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DSDLIMAGE_VENDORED=OFF
-DSDLIMAGE_BACKEND_STB=OFF
-DSDLIMAGE_JPG=ON
-DSDLIMAGE_PNG=ON
-DSDLIMAGE_WEBP=ON
-DSDLIMAGE_TIF=ON
-DSDLIMAGE_JXL=ON
-DSDLIMAGE_AVIF=ON
-DSDLIMAGE_JPG_SHARED=OFF
-DSDLIMAGE_JXL_SHARED=OFF
-DSDLIMAGE_PNG_SHARED=OFF
-DSDLIMAGE_TIF_SHARED=OFF
-DSDLIMAGE_WEBP_SHARED=OFF
-DSDLIMAGE_AVIF_SHARED=OFF
"
