CLANDRO_PKG_HOMEPAGE=https://xorg.freedesktop.org/
CLANDRO_PKG_DESCRIPTION="X11 Xinerama extension library"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.1.6"
CLANDRO_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libXinerama-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=d00fc1599c303dc5cbc122b8068bdc7405d6fcb19060f4597fc51bd3a8be51d7
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libx11, libxext"
CLANDRO_PKG_BUILD_DEPENDS="xorgproto"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="--enable-malloc0returnsnull"
