CLANDRO_PKG_HOMEPAGE="https://fennel-lang.org"
CLANDRO_PKG_DESCRIPTION="A Lisp that compiles to Lua"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.6.1"
CLANDRO_PKG_SRCURL="https://git.sr.ht/~technomancy/fennel/archive/$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=f0f188e9a4424851d9263ab69302b6b2ffc5c6efb67a25fffc52187a29c94024
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="lua54"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true

clandro_step_pre_configure() {
	export LUA_VERSION=5.4
	export LUA=lua5.4
}
