CLANDRO_PKG_HOMEPAGE=https://github.com/eja/eja
CLANDRO_PKG_DESCRIPTION="eja micro web server"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="18.4.19"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/eja/eja/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=3cccd82430d5b555d1d83f05840749be65b2763221f48fff1ed666bb063099e6
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="DESTDIR=${CLANDRO_PREFIX} EJA_PATH=${CLANDRO_PREFIX} EJA_PATH_BIN=${CLANDRO_PREFIX}/bin EJA_PATH_LIB=${CLANDRO_PREFIX}/lib prefix=/"
CLANDRO_PKG_BUILD_IN_SRC=true
