CLANDRO_PKG_HOMEPAGE=https://github.com/jbeder/yaml-cpp
CLANDRO_PKG_DESCRIPTION="A YAML parser and emitter in C++ matching the YAML 1.2 spec"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.9.0"
CLANDRO_PKG_SRCURL=https://github.com/jbeder/yaml-cpp/archive/refs/tags/yaml-cpp-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=25cb043240f828a8c51beb830569634bc7ac603978e0f69d6b63558dadefd49a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DYAML_BUILD_SHARED_LIBS=ON
-DINSTALL_GTEST=OFF
"
