CLANDRO_PKG_HOMEPAGE=https://myrepos.branchable.com/
CLANDRO_PKG_DESCRIPTION="Tool to manage all your version control repos"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.20180726
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=https://deb.debian.org/debian/pool/main/m/myrepos/myrepos_$CLANDRO_PKG_VERSION.tar.xz
CLANDRO_PKG_SHA256=9e9e4c114aae22e0aac51ecbc8d84ae617a5e5dfa979fab0d3bc42945f603f1e
CLANDRO_PKG_DEPENDS="git, perl"
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
