CLANDRO_PKG_HOMEPAGE=https://github.com/DaveGamble/cJSON
CLANDRO_PKG_DESCRIPTION="Ultralightweight JSON parser in ANSI C"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.7.19"
CLANDRO_PKG_SRCURL=https://github.com/DaveGamble/cJSON/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=7fa616e3046edfa7a28a32d5f9eacfd23f92900fe1f8ccd988c1662f30454562
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DENABLE_CJSON_UTILS=ON
"
