CLANDRO_SUBPKG_DESCRIPTION="ASP.NET Core 9.0 Targeting Pack"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_DEPENDS="dotnet-host"
CLANDRO_SUBPKG_INCLUDE=$(cat "${CLANDRO_PKG_TMPDIR}"/aspnetcore-targeting-pack.txt)
