CLANDRO_SUBPKG_DESCRIPTION=".NET 9.0 SDK Managed Debug Symbols"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_DEPENDS="dotnet-sdk-9.0"
CLANDRO_SUBPKG_INCLUDE=$(cat "${CLANDRO_PKG_TMPDIR}"/dotnet-sdk-dbg.txt)
