CLANDRO_SUBPKG_DESCRIPTION=".NET 9.0 Host Resolver"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_DEPENDS="dotnet-host"
CLANDRO_SUBPKG_INCLUDE=$(cat "${CLANDRO_PKG_TMPDIR}"/dotnet-hostfxr.txt)
