CLANDRO_PKG_HOMEPAGE=https://github.com/ArthurSonzogni/FTXUI
CLANDRO_PKG_DESCRIPTION="A simple C++ library for terminal based user interface"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.1.9"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/ArthurSonzogni/FTXUI/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=45819c1e54914783d4a1ca5633885035d74146778a1f74e1213cdb7b76340e71
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
CLANDRO_PKG_AUTO_UPDATE=true
