CLANDRO_PKG_HOMEPAGE=http://www.underbit.com/products/mad/
CLANDRO_PKG_DESCRIPTION="MAD ID3 tag manipulation library"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.16.4"
CLANDRO_PKG_SRCURL="https://codeberg.org/tenacityteam/libid3tag/archive/${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=ceb88ada1aa867c87c1d748a8aa40e68db5b0d2df636a9dab0ab1f7741d5e009
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="zlib"
CLANDRO_PKG_BREAKS="libid3tag-dev"
CLANDRO_PKG_REPLACES="libid3tag-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
"
