CLANDRO_PKG_HOMEPAGE=https://github.com/dylanaraps/fff
CLANDRO_PKG_DESCRIPTION="A simple file manager written in bash"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=2.2
CLANDRO_PKG_SRCURL=https://github.com/dylanaraps/fff/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=45f6e1091986c892ea45e1ac82f2d7f5417cfb343dc569d2625b5980e6bcfb62
CLANDRO_PKG_DEPENDS="bash"
CLANDRO_PKG_SUGGESTS="w3m-img, xdotool"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
