CLANDRO_PKG_HOMEPAGE=https://github.com/KhronosGroup/Vulkan-Utility-Libraries
CLANDRO_PKG_DESCRIPTION="Utility Libraries for Vulkan"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.4.351"
CLANDRO_PKG_SRCURL=https://github.com/KhronosGroup/Vulkan-Utility-Libraries/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=6de5c9834e5cdfee57ed951a74b6220b6ce2aa2bfb1edcb7d409e559d865e305
CLANDRO_PKG_BUILD_DEPENDS="libc++, vulkan-headers (=${CLANDRO_PKG_VERSION})"
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_UPDATE_VERSION_REGEXP="\d+.\d+.\d+"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
"
