# Contributor: @librehat
CLANDRO_PKG_HOMEPAGE=https://github.com/google/flatbuffers
CLANDRO_PKG_DESCRIPTION="Memory Efficient Serialization Library"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="25.12.19-2026-02-06-03fffb2"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://github.com/google/flatbuffers/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=ccbce58684691de1e7d51f5e87786266b37d06ab66e9dfe2d0ec106fe50aace0
CLANDRO_PKG_REPOLOGY_METADATA_VERSION="${CLANDRO_PKG_VERSION%%-*}"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DFLATBUFFERS_BUILD_SHAREDLIB=ON
-DFLATBUFFERS_BUILD_TESTS=OFF
"
