CLANDRO_PKG_HOMEPAGE=https://muennich.github.io/id3ted/
CLANDRO_PKG_DESCRIPTION="A command line id3 tag editor"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.0
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/muennich/id3ted/archive/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=b661514637278b00930cc13ef22f46530baadcf9f3f4ee4b7cb210b0d46b18f1
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="file, libc++, taglib"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
