CLANDRO_PKG_HOMEPAGE=https://github.com/Tencent/rapidjson/
CLANDRO_PKG_DESCRIPTION="Fast JSON parser/generator for C++ with SAX/DOM style API"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.1.0"
CLANDRO_PKG_REVISION=7
CLANDRO_PKG_SRCURL=https://github.com/Tencent/rapidjson/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DRAPIDJSON_BUILD_EXAMPLES=OFF
"
