CLANDRO_PKG_HOMEPAGE=http://dushistov.github.io/sdcv/
CLANDRO_PKG_DESCRIPTION="StarDict Console Version"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.5.5
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/Dushistov/sdcv/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=4d2519e8f8479b9301dc91e9cda3e1eefef19970ece0e8c05f0c7b7ade5dc94b
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="glib, libc++, readline, zlib"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DENABLE_NLS=off"
