CLANDRO_PKG_HOMEPAGE=https://www.opencode.net/trialuser/qt6ct/
CLANDRO_PKG_DESCRIPTION="Qt 6 Configuration Utility"
CLANDRO_PKG_LICENSE="BSD 2-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.11"
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=https://www.opencode.net/trialuser/qt6ct/-/archive/${CLANDRO_PKG_VERSION}/qt6ct-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=32cd06cb4e801362676194ec6c3378498c81eb9484c57870fee3f7d5952ebe1f
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtsvg"
CLANDRO_PKG_BUILD_DEPENDS="qt6-qttools"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DPLUGINDIR=${CLANDRO_PREFIX}/lib/qt6/plugins
"
