CLANDRO_PKG_HOMEPAGE=https://github.com/CNugteren/CLBlast
CLANDRO_PKG_DESCRIPTION="Tuned OpenCL BLAS"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.7.0"
CLANDRO_PKG_SRCURL=https://github.com/CNugteren/CLBlast/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=cac83330a6110214f2b7efc8e46062536f40ba96122f3b2a074a51497d8ca9e7
CLANDRO_PKG_DEPENDS="libc++, ocl-icd"
CLANDRO_PKG_BUILD_DEPENDS="opencl-headers"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DNETLIB=ON
"
