CLANDRO_PKG_HOMEPAGE=https://github.com/KhronosGroup/SPIRV-LLVM-Translator
CLANDRO_PKG_DESCRIPTION="SPIR-V LLVM Translator"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="21.1.7"
CLANDRO_PKG_SRCURL=https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=1a00e06eba69c24ded4ed5708ef3c55ad8786227017271fc335d3cc9abad2def
CLANDRO_PKG_DEPENDS="libc++, libllvm (<< $CLANDRO_LLVM_NEXT_MAJOR_VERSION)"
CLANDRO_PKG_BUILD_DEPENDS="libllvm-static, spirv-headers, spirv-tools"
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="21.\d+\.\d+"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBASE_LLVM_VERSION=${CLANDRO_LLVM_VERSION}
-DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=${CLANDRO_PREFIX}
"
