CLANDRO_PKG_HOMEPAGE=https://zeromq.org/
CLANDRO_PKG_DESCRIPTION="High-level C binding for ZeroMQ"
CLANDRO_PKG_LICENSE="MPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=4.2.1
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=https://github.com/zeromq/czmq/releases/download/v${CLANDRO_PKG_VERSION}/czmq-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=5d720a204c2a58645d6f7643af15d563a712dad98c9d32c1ed913377daa6ac39
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="liblz4, libuuid, libzmq"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="--enable-drafts=no"

clandro_step_pre_configure() {
	CFLAGS+=" -DCZMQ_HAVE_ANDROID=1"
	LDFLAGS+=" -llog"
	autoconf
}
