CLANDRO_PKG_HOMEPAGE=http://www.grinninglizard.com/tinyxml2/
CLANDRO_PKG_DESCRIPTION="A simple, small, efficient, C++ XML parser"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="11.0.0"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/leethomason/tinyxml2/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=5556deb5081fb246ee92afae73efd943c889cef0cafea92b0b82422d6a18f289
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
