# Contributor: @DLC01
CLANDRO_PKG_HOMEPAGE=https://gitlab.com/ecodis/exhale
CLANDRO_PKG_DESCRIPTION="Open source xHE-AAC encoder"
CLANDRO_PKG_LICENSE="custom"
CLANDRO_PKG_LICENSE_FILE="include/License.htm"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.2.2RC+really1.2.2"
CLANDRO_PKG_SRCURL="https://gitlab.com/ecodis/exhale/-/archive/v${CLANDRO_PKG_VERSION#*really}/exhale-v${CLANDRO_PKG_VERSION#*really}.tar.gz"
CLANDRO_PKG_REPOLOGY_METADATA_VERSION="${CLANDRO_PKG_VERSION#*really}"
CLANDRO_PKG_SHA256=a46a085e3f8049ece2cba5ab3dd80e85fd198e81277b5292ca198a25a80088f1
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
