CLANDRO_PKG_HOMEPAGE=https://simdutf.github.io/simdutf/
CLANDRO_PKG_DESCRIPTION="Unicode validation and transcoding at billions of characters per second"
CLANDRO_PKG_LICENSE="Apache-2.0, MIT"
CLANDRO_PKG_LICENSE_FILE="LICENSE-APACHE, LICENSE-MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="9.0.0"
CLANDRO_PKG_SRCURL=https://github.com/simdutf/simdutf/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=fd2ce975f29809a975a8da8843cfb3a7265af3f71be548f199d23cf65e101764
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DSIMDUTF_TESTS=OFF
-DSIMDUTF_TOOLS=OFF
-DSIMDUTF_BENCHMARKS=OFF
"
