CLANDRO_PKG_HOMEPAGE=https://github.com/WebAssembly/binaryen
CLANDRO_PKG_DESCRIPTION="Binaryen is a compiler and toolchain infrastructure library for WebAssembly"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="129"
CLANDRO_PKG_SRCURL=https://github.com/WebAssembly/binaryen/archive/refs/tags/version_${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=326f03e3a8b9eddc63cd9d6ff943bee86dae6f736c9f217e58530350381b011a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="\d+"
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_TESTS=OFF
-DBYN_ENABLE_LTO=ON
"
