CLANDRO_PKG_HOMEPAGE=https://giflib.sourceforge.net/
CLANDRO_PKG_DESCRIPTION="A library for reading and writing gif images"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="5.2.2"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL="https://downloads.sourceforge.net/project/giflib/giflib-5.x/giflib-${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=be7ffbd057cadebe2aa144542fd90c6838c6a083b5e8a9048b8ee3b66b29d5fb
CLANDRO_PKG_BREAKS="giflib-dev"
CLANDRO_PKG_REPLACES="giflib-dev"
CLANDRO_PKG_BUILD_IN_SRC=true
