CLANDRO_PKG_HOMEPAGE=https://www.pixman.org/
CLANDRO_PKG_DESCRIPTION="Low-level library for pixel manipulation"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.46.4"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://cairographics.org/releases/pixman-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=d09c44ebc3bd5bee7021c79f922fe8fb2fb57f7320f55e97ff9914d2346a591c
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BREAKS="libpixman-dev"
CLANDRO_PKG_REPLACES="libpixman-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-Dlibpng=disabled"
