CLANDRO_PKG_HOMEPAGE=https://github.com/python-xlib/python-xlib
CLANDRO_PKG_DESCRIPTION="The Python X Library"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.33
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/python-xlib/python-xlib/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=e10d1b49655800bffe0fbb5eb31eeef915a4421952ef006d468d53d34901f6f8
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="python, python-pip"
CLANDRO_PKG_PYTHON_COMMON_BUILD_DEPS="wheel"
CLANDRO_PKG_PYTHON_TARGET_DEPS="'six>=1.10.0'"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
