CLANDRO_PKG_HOMEPAGE=https://osm2pgsql.org/
CLANDRO_PKG_DESCRIPTION="osm2pgsql imports OpenStreetMap (OSM) data into a PostgreSQL/PostGIS database"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.2.0"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL="https://github.com/openstreetmap/osm2pgsql/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=567dad078f8a66d6d706ac1876b5251b688109d16974909d89ce2056d6e9f258
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="boost, libbz2, libc++, libexpat, lua54, postgresql, proj, zlib, nlohmann-json"
CLANDRO_PKG_EXCLUDED_ARCHES="arm, i686"
CLANDRO_PKG_BUILD_DEPENDS="boost-headers"
CLANDRO_PKG_GROUPS="science"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DEXTERNAL_FMT=OFF
"
