CLANDRO_SUBPKG_INCLUDE="bin/php-fpm etc/php-fpm.* share/man/man8/php-fpm.8.gz var/service/php-fpm"
CLANDRO_SUBPKG_CONFFILES="etc/php-fpm.conf etc/php-fpm.d/www.conf"
CLANDRO_SUBPKG_DESCRIPTION="FastCGI Process Manager for PHP"
CLANDRO_SUBPKG_BREAKS="php (<< 8.1.12)"
CLANDRO_SUBPKG_REPLACES="php (<< 8.1.12)"
