CLANDRO_PKG_HOMEPAGE=https://bellard.org/quickjs/
CLANDRO_PKG_DESCRIPTION="QuickJS is a small and embeddable Javascript engine"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2:2025.09.13.2"
_VERSION="${CLANDRO_PKG_VERSION:2}"
CLANDRO_PKG_SRCURL="https://bellard.org/quickjs/quickjs-${_VERSION//./-}.tar.xz"
CLANDRO_PKG_SHA256=996c6b5018fc955ad4d06426d0e9cb713685a00c825aa5c0418bd53f7df8b0b4
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="
CROSS_PREFIX=${CLANDRO_HOST_PLATFORM}-
CONFIG_CLANG=y
CONFIG_DEFAULT_AR=y
-W run-test262
-W run-test262-bn
prefix=$CLANDRO_PREFIX
"
