CLANDRO_PKG_HOMEPAGE=https://lxqt.github.io
CLANDRO_PKG_DESCRIPTION="The core library of LXQt"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.4.0"
CLANDRO_PKG_SRCURL="https://github.com/lxqt/liblxqt/releases/download/${CLANDRO_PKG_VERSION}/liblxqt-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=6627215644eb370723536274555743db52baed919db6ffc32ebc2bdf3cf8ee4a
CLANDRO_PKG_DEPENDS="kf6-kwindowsystem, libc++, libqtxdg, libx11, libxss, qt6-qtbase"
CLANDRO_PKG_BUILD_DEPENDS="lxqt-build-tools"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_BACKLIGHT_LINUX_BACKEND=OFF"
CLANDRO_PKG_AUTO_UPDATE=true
