CLANDRO_PKG_HOMEPAGE=https://xiph.org/flac/
CLANDRO_PKG_DESCRIPTION="FLAC (Free Lossless Audio Codec) library"
CLANDRO_PKG_LICENSE="GPL-2.0, LGPL-2.1, BSD 3-Clause"
CLANDRO_PKG_LICENSE_FILE="COPYING.GPL, COPYING.LGPL, COPYING.Xiph"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.5.0"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://downloads.xiph.org/releases/flac/flac-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=f2c1c76592a82ffff8413ba3c4a1299b6c7ab06c734dee03fd88630485c2b920
CLANDRO_PKG_DEPENDS="libc++, libogg"
CLANDRO_PKG_BREAKS="libflac-dev"
CLANDRO_PKG_REPLACES="libflac-dev"
CLANDRO_PKG_RM_AFTER_INSTALL="
share/doc/flac/FLAC.tag
share/doc/flac/api/
"
