CLANDRO_PKG_HOMEPAGE='https://userbase.kde.org/QCA'
CLANDRO_PKG_DESCRIPTION='Qt Cryptographic Architecture'
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.3.10"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://download.kde.org/stable/qca/${CLANDRO_PKG_VERSION}/qca-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=1c5b722da93d559365719226bb121c726ec3c0dc4c67dea34f1e50e4e0d14a02
CLANDRO_PKG_DEPENDS="botan3, ca-certificates, libc++, libnss, libsasl, openssl, qt6-qt5compat, qt6-qtbase"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DQT6=ON
-DBUILD_TESTS=OFF
-DQCA_MAN_INSTALL_DIR=$CLANDRO_PREFIX/share/man
"
