CLANDRO_PKG_HOMEPAGE=https://github.com/termux/libandroid-shmem
CLANDRO_PKG_DESCRIPTION="System V shared memory emulation on Android using ashmem"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.7
CLANDRO_PKG_SRCURL=https://github.com/termux/libandroid-shmem/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=1e5ff8459bc0a8c229dd8a94b27d119987e09ef3414331c2b5ebfff20b98e867
CLANDRO_PKG_BREAKS="libandroid-shmem-dev"
CLANDRO_PKG_REPLACES="libandroid-shmem-dev"
CLANDRO_PKG_BUILD_IN_SRC=true
