CLANDRO_PKG_HOMEPAGE=https://bitmath.org/code/mtdev/
CLANDRO_PKG_DESCRIPTION="A stand-alone library which transforms all variants of kernel MT events to the slotted type B protocol"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.1.7"
CLANDRO_PKG_SRCURL=https://bitmath.org/code/mtdev/mtdev-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=a55bd02a9af4dd266c0042ec608744fff3a017577614c057da09f1f4566ea32c
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_RM_AFTER_INSTALL="bin/mtdev-test"
