CLANDRO_PKG_HOMEPAGE=https://github.com/BoomerangDecompiler/boomerang
CLANDRO_PKG_DESCRIPTION="A general, open source machine code decompiler"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_LICENSE_FILE="LICENSE.TERMS"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.5.2
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/BoomerangDecompiler/boomerang/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=1d2c9c2f5de1a3e1d5fe3879e82bca268d1c49e6ba3d0a7848695f18c594384d
CLANDRO_PKG_DEPENDS="capstone, libc++, qt5-qtbase"
CLANDRO_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBOOMERANG_BUILD_UNIT_TESTS=OFF
"
