CLANDRO_PKG_HOMEPAGE=https://quick-lint-js.com/
CLANDRO_PKG_DESCRIPTION="Finds bugs in JavaScript programs"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.2.0"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=git+https://github.com/quick-lint/quick-lint-js
CLANDRO_PKG_GIT_BRANCH=$CLANDRO_PKG_VERSION
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_HOSTBUILD=true
CLANDRO_PKG_EXTRA_HOSTBUILD_CONFIGURE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_TESTING=OFF
-DQUICK_LINT_JS_USE_BUILD_TOOLS=$CLANDRO_PKG_HOSTBUILD_DIR/build-tools/
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"

clandro_step_host_build() {
	# https://quick-lint-js.com/contribute/build-from-source/cross-compiling/
	clandro_setup_cmake
	cmake -DCMAKE_BUILD_TYPE=Release -S "$CLANDRO_PKG_SRCDIR" -B build-tools $CLANDRO_PKG_EXTRA_HOSTBUILD_CONFIGURE_ARGS
	make -C build-tools quick-lint-js-build-tools $CLANDRO_PKG_EXTRA_MAKE_ARGS
}
