CLANDRO_PKG_HOMEPAGE=https://www.spice-space.org/
CLANDRO_PKG_DESCRIPTION="network protocol for sending USB device traffic over a network connection"
CLANDRO_PKG_LICENSE="GPL-2.0, LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.13.0
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://www.spice-space.org/download/usbredir/usbredir-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=4ba6faa02c0ae6deeb4c53883d66ab54b3a5899bead42ce4ded9568b9a7dc46e
CLANDRO_PKG_DEPENDS="glib, libusb"
