CLANDRO_PKG_HOMEPAGE="https://invent.kde.org/plasma/oxygen-sounds"
CLANDRO_PKG_DESCRIPTION="The Oxygen Sound Theme by KDE"
CLANDRO_PKG_LICENSE="LGPL-2.0-or-later"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.6.4"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/plasma/${CLANDRO_PKG_VERSION}/oxygen-sounds-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=ffd36dfe7c3d1627933678d45b626c4d15a1194096bf66b5145dfbe873ee1051
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BUILD_DEPENDS="extra-cmake-modules"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
