CLANDRO_SUBPKG_DESCRIPTION="units_cur Python script"
CLANDRO_SUBPKG_INCLUDE="
bin/units_cur
"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_DEPENDS="python, python-pip"
CLANDRO_SUBPKG_BREAKS="units (<< 2.22)"
CLANDRO_SUBPKG_REPLACES="units (<< 2.22)"
CLANDRO_SUBPKG_PYTHON_RUNTIME_DEPS="requests"
