CLANDRO_PKG_HOMEPAGE=https://www.airs.com/ian/uucp.html
CLANDRO_PKG_DESCRIPTION="The standard UUCP package of the Free Software Foundation"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.07
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://mirrors.kernel.org/gnu/uucp/uucp-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=060c15bfba6cfd1171ad81f782789032113e199a5aded8f8e0c1c5bd1385b62c
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
--infodir=$CLANDRO_PREFIX/share/info
--mandir=$CLANDRO_PREFIX/share/man
"
