CLANDRO_PKG_HOMEPAGE="https://logging.apache.org/log4cxx/latest_stable/index.html"
CLANDRO_PKG_DESCRIPTION="A logging framework for C++ patterned after Apache log4j"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.7.0"
CLANDRO_PKG_SRCURL="https://github.com/apache/logging-log4cxx/archive/refs/tags/rel/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=f4457bf3e6070bfa69689d44639f73e98d9bdb2324c7fe3cd5e949ec5902a2ba
CLANDRO_PKG_DEPENDS="apr, apr-util, libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DBUILD_TESTING=OFF
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP="rel/v\d+\.\d+\.\d+"
