CLANDRO_PKG_HOMEPAGE=https://docs.xfce.org/xfce/thunar/archive
CLANDRO_PKG_DESCRIPTION="This plugin allows one to extract and create archive from inside the Thunar file manager."
CLANDRO_PKG_LICENSE="LGPL-2.0"
CLANDRO_PKG_MAINTAINER="@Yisus7u7"
CLANDRO_PKG_VERSION="0.6.0"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://archive.xfce.org/src/thunar-plugins/thunar-archive-plugin/${CLANDRO_PKG_VERSION%.*}/thunar-archive-plugin-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=692708cd047c7a552f2f85fe2ee32f19c7d5be5bf695d0288e8cadf50289db06
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="glib, gtk3, libxfce4util, thunar"
CLANDRO_PKG_RECOMMENDS="file-roller"
