CLANDRO_PKG_HOMEPAGE=http://docopt.org
CLANDRO_PKG_DESCRIPTION="Command line arguments parser for C++11 and later"
CLANDRO_PKG_LICENSE="BSL-1.0, MIT"
CLANDRO_PKG_LICENSE_FILE="LICENSE-Boost-1.0, LICENSE-MIT"
CLANDRO_PKG_MAINTAINER="Henrik Grimler @Grimler91"
CLANDRO_PKG_VERSION=0.6.3
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=https://github.com/docopt/docopt.cpp/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=28af5a0c482c6d508d22b14d588a3b0bd9ff97135f99c2814a5aa3cbff1d6632
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"

clandro_step_pre_configure() {
	LDFLAGS+=" $($CC -print-libgcc-file-name)"
}
