CLANDRO_PKG_HOMEPAGE=http://libpipeline.nongnu.org/
CLANDRO_PKG_DESCRIPTION="C library for manipulating pipelines of subprocesses in a flexible and convenient way"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.5.8
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://download.savannah.nongnu.org/releases/libpipeline/libpipeline-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=1b1203ca152ccd63983c3f2112f7fe6fa5afd453218ede5153d1b31e11bb8405
CLANDRO_PKG_BREAKS="libpipeline-dev"
CLANDRO_PKG_REPLACES="libpipeline-dev"
