CLANDRO_PKG_HOMEPAGE=https://elinux.org/Electric_Fence
CLANDRO_PKG_DESCRIPTION="Electric Fence (eFence) malloc memory debugger"
CLANDRO_PKG_LICENSE=GPL-2.0
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.2.7"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://deb.debian.org/debian/pool/main/e/electric-fence/electric-fence_${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=9544dd4212ed1c34dc6de06c83324e1a8dc866a1949b8c69b7ba5bedcea373aa
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_IN_SRC=true
