CLANDRO_PKG_HOMEPAGE=https://libusb.info/hidapi
CLANDRO_PKG_DESCRIPTION="Simple cross-platform library for communicating with HID devices"
CLANDRO_PKG_LICENSE="GPL-3.0, BSD 3-Clause, custom"
CLANDRO_PKG_LICENSE_FILE="LICENSE.txt, LICENSE-gpl3.txt, LICENSE-bsd.txt, LICENSE-orig.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.14.0
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://github.com/libusb/hidapi/archive/refs/tags/hidapi-${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=a5714234abe6e1f53647dd8cba7d69f65f71c558b7896ed218864ffcf405bcbd
CLANDRO_PKG_DEPENDS="libiconv, libusb"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
