CLANDRO_PKG_HOMEPAGE=https://github.com/dstosberg/odt2txt
CLANDRO_PKG_DESCRIPTION="Simple converter from OpenDocument Text to plain text"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.5
CLANDRO_PKG_REVISION=5
CLANDRO_PKG_SRCURL=https://github.com/dstosberg/odt2txt/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=23a889109ca9087a719c638758f14cc3b867a5dcf30a6c90bf6a0985073556dd
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="libiconv, libzip, zlib"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="HAVE_LIBZIP=1 DESTDIR=$CLANDRO_PREFIX"
