CLANDRO_PKG_HOMEPAGE=https://github.com/AMDmi3/cavezofphear
CLANDRO_PKG_DESCRIPTION="A Boulder Dash like game for consoles/terminals"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.6.2"
CLANDRO_PKG_SRCURL=https://github.com/AMDmi3/cavezofphear/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=32f8d535b3bbd6d037371ff80127f02dfb7ef4eca066c753efff1e09c28030af
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libandroid-support, ncurses"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DSYSTEMWIDE=ON -DWITH_MANPAGE=OFF"
CLANDRO_PKG_GROUPS="games"
