CLANDRO_PKG_HOMEPAGE=https://git.causal.agency/pounce
CLANDRO_PKG_DESCRIPTION="A multi-client, TLS-only IRC bouncer"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=3.1
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://git.causal.agency/pounce/snapshot/pounce-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=97f245556b1cc940553fca18f4d7d82692e6c11a30f612415e5e391e5d96604e
CLANDRO_PKG_DEPENDS="libcrypt, libretls"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
--mandir=$CLANDRO_PREFIX/share/man
"
CLANDRO_PKG_EXTRA_MAKE_ARGS="all"
