CLANDRO_PKG_HOMEPAGE=https://www.fetchmail.info/
CLANDRO_PKG_DESCRIPTION="A remote-mail retrieval utility"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_LICENSE_FILE="COPYING"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.6.4"
CLANDRO_PKG_SRCURL=https://sourceforge.net/projects/fetchmail/files/branch_${CLANDRO_PKG_VERSION:0:3}/fetchmail-$CLANDRO_PKG_VERSION.tar.xz
CLANDRO_PKG_SHA256=efe01690d22bda359a579c77e2b0072658a092bff490ec0478a212c6b7d0eb70
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="openssl"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="--with-ssl=$CLANDRO_PREFIX"
CLANDRO_PKG_RM_AFTER_INSTALL="lib/python${CLANDRO_PYTHON_VERSION}/site-packages/__pycache__"
CLANDRO_PKG_PYTHON_COMMON_BUILD_DEPS="wheel"
