CLANDRO_PKG_HOMEPAGE=https://www.kde.org/
CLANDRO_PKG_DESCRIPTION="Qt 5 addon providing access to numerous types of archives (KDE)"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="5.116.0"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/frameworks/${CLANDRO_PKG_VERSION%.*}/karchive-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=1663e3c970b84063ece7f28548a87c97bc7592e79da0a0afaa4f6354f8dea30a
CLANDRO_PKG_AUTO_UPDATE=false
CLANDRO_PKG_DEPENDS="libbz2, libc++, liblzma, qt5-qtbase, zlib, zstd"
CLANDRO_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
