CLANDRO_PKG_HOMEPAGE=https://www.music.mcgill.ca/~gary/rtmidi/
CLANDRO_PKG_DESCRIPTION="A set of C++ classes that provides a common API for realtime MIDI input/output"
CLANDRO_PKG_LICENSE="custom"
CLANDRO_PKG_LICENSE_FILE="LICENSE"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=5.0.0
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/thestk/rtmidi/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c7923e4eee82b06c007435892cb2c3212d9007fa482c6b718943bda71c02c5a7
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_FORCE_CMAKE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DRTMIDI_API_ALSA=OFF
-DRTMIDI_API_JACK=OFF
"
