CLANDRO_PKG_HOMEPAGE=https://tildegit.org/tomasino/pb
CLANDRO_PKG_DESCRIPTION="A helper utility for using 0x0 pastebin services"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=2022.11.03
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/jamestomasino/pb/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=e76ca01fe77392695a43ef7ea9c27b3e89b7e2af5750d41b35916e1fd1d66098
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"

clandro_step_make() {
	:
}
