CLANDRO_PKG_HOMEPAGE=https://github.com/libsdl-org/SDL_ttf
CLANDRO_PKG_DESCRIPTION="A library that allows you to use TrueType fonts in SDL applications (version 3)"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_LICENSE_FILE="LICENSE.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.2.2"
CLANDRO_PKG_SRCURL="https://github.com/libsdl-org/SDL_ttf/releases/download/release-${CLANDRO_PKG_VERSION}/SDL3_ttf-${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=63547d58d0185c833213885b635a2c0548201cc8f301e6587c0be1a67e1e045d
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="freetype, harfbuzz, sdl3"

CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DSDLTTF_VENDORED=OFF
-DSDLTTF_PLUTOSVG=OFF
-DSDLTTF_SAMPLES=OFF
-DSDLTTF_HARFBUZZ=ON
-DSDLTTF_FREETYPE=ON
"
