CLANDRO_PKG_HOMEPAGE=https://github.com/radare/ired
CLANDRO_PKG_DESCRIPTION="Minimalist hexadecimal editor"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.6
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/radare/ired/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c15d37b96b1a25c44435d824bd7ef1f9aea9dc191be14c78b689d3156312d58a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_BUILD_IN_SRC=true

clandro_step_pre_configure() {
	CFLAGS+=" $LDFLAGS"
}
