CLANDRO_PKG_HOMEPAGE=https://matrix.org/docs/projects/other/olm/
CLANDRO_PKG_DESCRIPTION="An implementation of the Double Ratchet cryptographic ratchet"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.2.16"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://gitlab.matrix.org/matrix-org/olm/-/archive/${CLANDRO_PKG_VERSION}/olm-${CLANDRO_PKG_VERSION}.tar.bz2
CLANDRO_PKG_SHA256=327cfcb81ef0c42f4b1d5c24b25d56932b57d64ccd9f00ed919a893a43333411
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
