CLANDRO_PKG_HOMEPAGE="https://github.com/danvratil/qcoro"
CLANDRO_PKG_DESCRIPTION="C++ Coroutines for Qt"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@termux-user"
CLANDRO_PKG_VERSION="0.13.0"
CLANDRO_PKG_SRCURL="https://github.com/danvratil/qcoro/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=4bff7513c5c8e301b66308df05795043b1792ed16381a484e5c990171b8ff19e
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtdeclarative, qt6-qtwebsockets"
CLANDRO_PKG_BUILD_DEPENDS="cmake, git"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
"
