CLANDRO_PKG_HOMEPAGE=https://github.com/ryanmjacobs/c
CLANDRO_PKG_DESCRIPTION="Compile and execute C 'scripts' in one go!"
CLANDRO_PKG_LICENSE=MIT
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.15.1"
CLANDRO_PKG_SRCURL=$CLANDRO_PKG_HOMEPAGE/archive/v$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=ecfad78cb0ab56da44dcfed805f5c261ddefd6dc4a4e57eb2dcfcffa85330605
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_DEPENDS=bash
CLANDRO_PKG_PLATFORM_INDEPENDENT=true

clandro_step_make_install() {
	local bin="$(basename $CLANDRO_PKG_HOMEPAGE)"
	install -D "$bin" -t "$CLANDRO_PREFIX/bin"
}
