CLANDRO_PKG_HOMEPAGE=https://github.com/dylanaraps/neofetch
CLANDRO_PKG_DESCRIPTION="Simple system information script"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=7.1.0
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/dylanaraps/neofetch/archive/refs/tags/${CLANDRO_PKG_VERSION}/neofetch-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="bash"
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX SYSCONFDIR=$CLANDRO_PREFIX/etc"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
