CLANDRO_SUBPKG_DESCRIPTION="Rust source code files"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_BREAKS="rust (<< 1.74.1-1)"
CLANDRO_SUBPKG_REPLACES="rust (<< 1.74.1-1)"
CLANDRO_SUBPKG_INCLUDE="
lib/rustlib/src
"
