CLANDRO_PKG_HOMEPAGE=https://openal-soft.org/
CLANDRO_PKG_DESCRIPTION="Software implementation of the OpenAL API"
CLANDRO_PKG_LICENSE="LGPL-2.0, BSD 3-Clause"
CLANDRO_PKG_LICENSE_FILE="BSD-3Clause, COPYING"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.25.1"
CLANDRO_PKG_SRCURL="https://github.com/kcat/openal-soft/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=5f8efe8dfba5e9307a50251ba615ace857c7fa9dddfe34130b83e213d7f7cf24
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BREAKS="openal-soft-dev"
CLANDRO_PKG_REPLACES="openal-soft-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DALSOFT_UTILS=ON
-DALSOFT_NO_CONFIG_UTIL=ON
-DALSOFT_EXAMPLES=ON
-DALSOFT_TESTS=OFF
-DALSOFT_REQUIRE_OPENSL=ON
"

clandro_step_pre_configure() {
	if [[ "$CLANDRO_ON_DEVICE_BUILD" == "false" ]]; then
		CLANDRO_PKG_EXTRA_CONFIGURE_ARGS+=" -DCMAKE_CXX_COMPILER_CLANG_SCAN_DEPS=${CLANDRO_STANDALONE_TOOLCHAIN}/bin/clang-scan-deps"
	fi

	CLANDRO_PKG_EXTRA_CONFIGURE_ARGS+=" -DOPENSL_LIBRARY=$CLANDRO_STANDALONE_TOOLCHAIN/sysroot/usr/lib/$CLANDRO_HOST_PLATFORM/$CLANDRO_PKG_API_LEVEL/libOpenSLES.so"
}
