CLANDRO_SUBPKG_DESCRIPTION="ASP.NET Core 8.0 Runtime Managed Debug Symbols"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_DEPENDS="aspnetcore-runtime-8.0"
CLANDRO_SUBPKG_INCLUDE=$(cat "${CLANDRO_PKG_TMPDIR}"/aspnetcore-runtime-dbg.txt)
