CLANDRO_PKG_HOMEPAGE=https://capnproto.org/
CLANDRO_PKG_DESCRIPTION="Data interchange format and capability-based RPC system"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.4.0"
CLANDRO_PKG_SRCURL=https://github.com/capnproto/capnproto/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=d14a9149b79c055fee9d5aa778defe8e8cee0d2a11f0729865cd30dcc345eef2
CLANDRO_PKG_UPDATE_TAG_TYPE=newest-tag
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_FORCE_CMAKE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
-DWITH_FIBERS=OFF
"
