CLANDRO_PKG_HOMEPAGE=https://libsndfile.github.io/libsamplerate/
CLANDRO_PKG_DESCRIPTION="A library for performing sample rate conversion of audio data"
CLANDRO_PKG_LICENSE="BSD 2-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.2.2
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_SRCURL=https://github.com/libsndfile/libsamplerate/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=16e881487f184250deb4fcb60432d7556ab12cb58caea71ef23960aec6c0405a
CLANDRO_PKG_FORCE_CMAKE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DLIBSAMPLERATE_EXAMPLES=OFF
-DLIBSAMPLERATE_TESTS=OFF
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
