CLANDRO_SUBPKG_DESCRIPTION=".NET 10.0 Host"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_CONFLICTS="dotnet-host-8.0, dotnet-host-9.0"
CLANDRO_SUBPKG_INCLUDE=$(cat "${CLANDRO_PKG_TMPDIR}"/dotnet-host.txt)
