CLANDRO_PKG_HOMEPAGE=https://git.causal.agency/catgirl
CLANDRO_PKG_DESCRIPTION="A TLS-only terminal IRC client"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.2a"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://git.causal.agency/catgirl/snapshot/catgirl-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c6d760aaee134e052586def7a9103543f7281fde6531fbcb41086470794297c2
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libandroid-support, libretls, ncurses, openssl"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
--mandir=$CLANDRO_PREFIX/share/man
"
CLANDRO_PKG_EXTRA_MAKE_ARGS="catgirl"
