CLANDRO_PKG_HOMEPAGE=https://thrift.apache.org
CLANDRO_PKG_DESCRIPTION="Scalable cross-language services framework for IPC/RPC"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.23.0"
CLANDRO_PKG_SRCURL="https://downloads.apache.org/thrift/${CLANDRO_PKG_VERSION}/thrift-${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=1859d932d2ae1f13d16c5a196931208c116310a5ff50f2bfd11d3db03be8f46f
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_DEPENDS="libc++, openssl"
CLANDRO_PKG_BUILD_DEPENDS="boost, boost-headers"
# cmake options are copied from https://github.com/apache/arrow/blob/main/cpp/cmake_modules/ThirdpartyToolchain.cmake
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_COMPILER=OFF
-DBUILD_EXAMPLES=OFF
-DBUILD_SHARED_LIBS=ON
-DBUILD_TUTORIALS=OFF
-DWITH_AS3=OFF
-DWITH_CPP=ON
-DWITH_C_GLIB=OFF
-DWITH_JAVA=OFF
-DWITH_JAVASCRIPT=OFF
-DWITH_LIBEVENT=OFF
-DWITH_NODEJS=OFF
-DWITH_PYTHON=OFF
-DWITH_QT5=OFF
-DWITH_ZLIB=OFF
"

clandro_step_pre_configure() {
	rm configure
}
