CLANDRO_PKG_HOMEPAGE=https://ssdb.io/
CLANDRO_PKG_DESCRIPTION="A Redis compatible NoSQL database stored on disk"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.9.9
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/ideawu/ssdb/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=a32009950114984d6e468e10d964b0ef1e846077b69d7c7615715fdfa01aaf6e
CLANDRO_PKG_DEPENDS="leveldb, libc++"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX/opt/ssdb"

clandro_step_pre_configure() {
	export TARGET_OS=OS_ANDROID_CROSSCOMPILE
}
