CLANDRO_SUBPKG_DESCRIPTION="Emscripten-compatible LLVM"
CLANDRO_SUBPKG_DEPENDS="libc++"
CLANDRO_SUBPKG_DEPEND_ON_PARENT=false
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=false
CLANDRO_SUBPKG_INCLUDE="opt/emscripten-llvm"
