CLANDRO_PKG_HOMEPAGE=https://launchpad.net/libdbusmenu-qt
CLANDRO_PKG_DESCRIPTION="dbusmenu library for Qt"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.9.3+16.04.20160218-0ubuntu1"
CLANDRO_PKG_REVISION=6
CLANDRO_PKG_SRCURL="https://github.com/unity8-team/libdbusmenu-qt/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=bc2c3960c0c6b520e42e652b6a71b769cff6cb651adece92d2a0bc6bdff37c29
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="libc++, qt5-qtbase"
CLANDRO_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DUSE_QT4=OFF
-DUSE_QT5=ON
-DWITH_DOC=OFF
"
