CLANDRO_PKG_HOMEPAGE=https://dl.matroska.org/downloads/libmatroska/
CLANDRO_PKG_DESCRIPTION="Matroska library"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.7.1
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/Matroska-Org/libmatroska/archive/refs/tags/release-$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=64763443947833e6c17f1f555f4bb0df6c9f91881810d9d5e0f0bad3622d308b
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_DEPENDS="libc++, libebml"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
