CLANDRO_PKG_HOMEPAGE=https://darwinsys.com/file/
CLANDRO_PKG_DESCRIPTION="Command-line tool that tells you in words what kind of data a file contains"
CLANDRO_PKG_LICENSE="BSD 2-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=5.47
CLANDRO_PKG_SRCURL=https://astron.com/pub/file/file-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=45672fec165cb4cc1358a2d76b5d57d22876dcb97ab169427ac385cbe1d5597a
CLANDRO_PKG_DEPENDS="zlib"
CLANDRO_PKG_BREAKS="file-dev"
CLANDRO_PKG_REPLACES="file-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_func_mmap_fixed_mapped=yes"
CLANDRO_PKG_EXTRA_MAKE_ARGS="FILE_COMPILE=$CLANDRO_PKG_HOSTBUILD_DIR/src/file"
CLANDRO_PKG_HOSTBUILD=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_GROUPS="base-devel"
