CLANDRO_PKG_HOMEPAGE=https://github.com/Matroska-Org/libebml
CLANDRO_PKG_DESCRIPTION="Extensible Binary Meta Language library"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.4.5"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/Matroska-Org/libebml/archive/refs/tags/release-$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=86c99573cd0957884f26547d1a8fa0c979e4d6d57484dfd387345846e6720f49
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
