CLANDRO_PKG_HOMEPAGE=https://www.kde.org/
CLANDRO_PKG_DESCRIPTION="Framework which lets applications perform actions as a privileged user (KDE)"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="5.116.0"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/frameworks/${CLANDRO_PKG_VERSION%.*}/kauth-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=ace1ee1ac0aa1b291c4c50c93fc3503b62318eeef0df0ee394a5a08da9691ff4
CLANDRO_PKG_AUTO_UPDATE=false
CLANDRO_PKG_DEPENDS="libc++, qt5-qtbase, kcoreaddons"
CLANDRO_PKG_BUILD_DEPENDS="extra-cmake-modules, qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
