CLANDRO_PKG_HOMEPAGE=https://cl-andro.github.io
CLANDRO_PKG_DESCRIPTION="Contains LICENSE files for common licenses"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=2.1
CLANDRO_PKG_AUTO_UPDATE=false
CLANDRO_PKG_SKIP_SRC_EXTRACT=true
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_ESSENTIAL=true

clandro_step_make_install() {
	mkdir -p "$CLANDRO_PREFIX/share/LICENSES"
	for LICENSE in "$CLANDRO_PKG_BUILDER_DIR/LICENSES/"*.txt; do
		cp -f "$LICENSE" "$CLANDRO_PREFIX/share/LICENSES/"
	done
}
