CLANDRO_PKG_HOMEPAGE=http://software.clapper.org/daemonize/
CLANDRO_PKG_DESCRIPTION="Run a command as a Unix daemon"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.7.8
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/bmc/daemonize/archive/refs/tags/release-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=20c4fc9925371d1ddf1b57947f8fb93e2036eb9ccc3b43a1e3678ea8471c4c60
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_func_setpgrp_void=yes"
CLANDRO_PKG_EXTRA_MAKE_ARGS="INSTALL_SBIN=$CLANDRO_PREFIX/bin"
