CLANDRO_PKG_HOMEPAGE=https://pugixml.org/
CLANDRO_PKG_DESCRIPTION="Light-weight, simple and fast XML parser for C++ with XPath support"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.15"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/zeux/pugixml/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=b39647064d9e28297a34278bfb897092bf33b7c487906ddfc094c9e8868bddcb
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
