CLANDRO_PKG_HOMEPAGE=https://github.com/radare/posixvala
CLANDRO_PKG_DESCRIPTION="Aims to bring back the posix profile for Vala"
CLANDRO_PKG_LICENSE="GPL-3.0, LGPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.2
CLANDRO_PKG_SRCURL=https://github.com/radare/posixvala/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=d35d1e333d7941e130e094b0f55d53132855b990a7df699c14061e0a0e6853e8
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"

clandro_step_make() {
	:
}
