CLANDRO_PKG_HOMEPAGE=https://mp3splt.sourceforge.net
CLANDRO_PKG_DESCRIPTION="Utility to split MP3, Ogg Vorbis and native FLAC files without decoding"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.9.2
CLANDRO_PKG_REVISION=10
CLANDRO_PKG_SRCURL=http://prdownloads.sourceforge.net/mp3splt/libmp3splt-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=30eed64fce58cb379b7cc6a0d8e545579cb99d0f0f31eb00b9acc8aaa1b035dc
CLANDRO_PKG_DEPENDS="libflac, libid3tag, libltdl, libmad, libogg, libvorbis, pcre"
CLANDRO_PKG_BREAKS="libmp3splt-dev"
CLANDRO_PKG_REPLACES="libmp3splt-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="--disable-cutter"
