CLANDRO_PKG_HOMEPAGE=https://github.com/vgmstream/vgmstream
CLANDRO_PKG_DESCRIPTION="A library for playback of various streamed audio formats used in video games"
CLANDRO_PKG_LICENSE="ISC"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2083"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://github.com/vgmstream/vgmstream/archive/refs/tags/r${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=22cec642df2ea4148849d64d5af384f156a1dbebd95567e00236833dd9dbe136
CLANDRO_PKG_REPOLOGY_METADATA_VERSION="r${CLANDRO_PKG_VERSION}"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_VERSION_REGEXP='\d+'
CLANDRO_PKG_DEPENDS="ffmpeg, libao, libjansson, libspeex, libvorbis, libmpg123"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_G719=OFF
-DUSE_ATRAC9=OFF
-DUSE_CELT=OFF
-DBUILD_AUDACIOUS=OFF
"
