CLANDRO_PKG_HOMEPAGE=https://github.com/wdas/ptex
CLANDRO_PKG_DESCRIPTION="Per-Face Texture Mapping for Production Rendering"
CLANDRO_PKG_LICENSE="BSD"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.5.2"
CLANDRO_PKG_SRCURL=https://github.com/wdas/ptex/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=dd95fbea4b50e9e68fd042f540fb83157a0ff25053066c3439d4527de3621d34
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="libc++, libdeflate"
CLANDRO_PKG_BUILD_DEPENDS="libdeflate-static"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_CXX_STANDARD=17
"
