CLANDRO_PKG_HOMEPAGE=https://biboumi.louiz.org/
CLANDRO_PKG_DESCRIPTION="An XMPP gateway that connects to IRC servers and translates between the two protocols"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=9.0
CLANDRO_PKG_REVISION=5
CLANDRO_PKG_SRCURL=https://github.com/louiz/biboumi/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=4d5bd5e21252ab4e79c14413afb922d69beba802519c9f38796f6c1372abac41
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="libc++, libexpat, libgcrypt, libiconv, libidn, libsqlite, libuuid"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DWITHOUT_BOTAN=ON
-DWITHOUT_POSTGRESQL=ON
-DWITHOUT_SYSTEMD=ON
-DWITHOUT_UDNS=ON
"
