CLANDRO_PKG_HOMEPAGE=https://www.freedesktop.org/wiki/Software/uchardet/
CLANDRO_PKG_DESCRIPTION="An encoding detector library"
CLANDRO_PKG_LICENSE="custom"
CLANDRO_PKG_LICENSE_FILE="COPYING"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.0.8
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://www.freedesktop.org/software/uchardet/releases/uchardet-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
