CLANDRO_PKG_HOMEPAGE=https://fcitx-im.org/
CLANDRO_PKG_DESCRIPTION="Fcitx Qt immodule & library"
CLANDRO_PKG_LICENSE="LGPL-2.1"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="5.1.13"
CLANDRO_PKG_SRCURL=https://github.com/fcitx/fcitx5-qt/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=74b2c43ca865ec9ede257bcd3bdadafc20f571900cb2440a4488335e4d4e91cc
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="fcitx5, libc++, libwayland, libx11, libxcb, libxkbcommon, qt6-qtbase"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_QT6PLUGINDIR=lib/qt6/plugins
-DENABLE_TEST=OFF
-DENABLE_QT4=OFF
-DENABLE_QT5=OFF
-DENABLE_QT6=ON
-DENABLE_QT6_WAYLAND_WORKAROUND=ON
"
