# Contributor: @Neo-Oli
CLANDRO_PKG_HOMEPAGE=https://github.com/signalapp/libsignal-protocol-c
CLANDRO_PKG_DESCRIPTION="Signal Protocol C Library"
CLANDRO_PKG_LICENSE="GPL-3.0"
CLANDRO_PKG_VERSION=2.3.3
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_MAINTAINER="Oliver Schmidhauser @Neo-Oli"
CLANDRO_PKG_SRCURL=https://github.com/signalapp/libsignal-protocol-c/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c22e7690546e24d46210ca92dd808f17c3102e1344cd2f9a370136a96d22319d
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="openssl"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"

clandro_step_pre_configure() {
	CLANDRO_PKG_EXTRA_CONFIGURE_ARGS+=" -DBUILD_SHARED_LIBS=ON"
	CLANDRO_PKG_EXTRA_CONFIGURE_ARGS+=" -DM_LIB=$CLANDRO_STANDALONE_TOOLCHAIN/sysroot/usr/lib/$CLANDRO_HOST_PLATFORM/$CLANDRO_PKG_API_LEVEL/libm.so"
}
