CLANDRO_PKG_HOMEPAGE=https://github.com/cl-andro/clandro-core-package
CLANDRO_PKG_DESCRIPTION="Utils and libraries for Termux core"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.4.0
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/cl-andro/clandro-core-package/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=af6299f341292ca98d1748a06e342fe29fbc9eb485a7c1ba5c9f91ba72b4f44a
CLANDRO_PKG_ESSENTIAL=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="CLANDRO_CORE_PKG__VERSION=${CLANDRO_PKG_VERSION} CLANDRO_CORE_PKG__ARCH=${CLANDRO_ARCH} \
CLANDRO__NAME=${CLANDRO__NAME} CLANDRO__LNAME=${CLANDRO__LNAME} \
CLANDRO__REPOS_HOST_ORG_NAME=${CLANDRO__REPOS_HOST_ORG_NAME} CLANDRO__REPOS_HOST_ORG_URL=${CLANDRO__REPOS_HOST_ORG_URL} \
CLANDRO_APP__NAME=${CLANDRO_APP__NAME} \
CLANDRO_APP__PACKAGE_NAME=${CLANDRO_APP__PACKAGE_NAME} CLANDRO_APP__DATA_DIR=${CLANDRO_APP__DATA_DIR} \
CLANDRO__ROOTFS=${CLANDRO__ROOTFS} CLANDRO__HOME=${CLANDRO__HOME} CLANDRO__PREFIX=${CLANDRO__PREFIX} \
CLANDRO__PREFIX__TMP_DIR=${CLANDRO__PREFIX__TMP_DIR} \
CLANDRO_ENV__S_ROOT=${CLANDRO_ENV__S_ROOT} \
CLANDRO_ENV__SS_CLANDRO=${CLANDRO_ENV__SS_CLANDRO} CLANDRO_ENV__S_CLANDRO=${CLANDRO_ENV__S_CLANDRO} \
CLANDRO_ENV__SS_CLANDRO_APP=${CLANDRO_ENV__SS_CLANDRO_APP} CLANDRO_ENV__S_CLANDRO_APP=${CLANDRO_ENV__S_CLANDRO_APP} \
CLANDRO_ENV__SS_CLANDRO_API_APP=${CLANDRO_ENV__SS_CLANDRO_API_APP} CLANDRO_ENV__S_CLANDRO_API_APP=${CLANDRO_ENV__S_CLANDRO_API_APP} \
CLANDRO_ENV__SS_CLANDRO_ROOTFS=${CLANDRO_ENV__SS_CLANDRO_ROOTFS} CLANDRO_ENV__S_CLANDRO_ROOTFS=${CLANDRO_ENV__S_CLANDRO_ROOTFS} \
CLANDRO_ENV__SS_CLANDRO_CORE=${CLANDRO_ENV__SS_CLANDRO_CORE} CLANDRO_ENV__S_CLANDRO_CORE=${CLANDRO_ENV__S_CLANDRO_CORE} \
CLANDRO_ENV__SS_CLANDRO_CORE__TESTS=${CLANDRO_ENV__SS_CLANDRO_CORE__TESTS} CLANDRO_ENV__S_CLANDRO_CORE__TESTS=${CLANDRO_ENV__S_CLANDRO_CORE__TESTS} \
CLANDRO_ENV__SS_CLANDRO_EXEC__TESTS=${CLANDRO_ENV__SS_CLANDRO_EXEC__TESTS} CLANDRO_ENV__S_CLANDRO_EXEC__TESTS=${CLANDRO_ENV__S_CLANDRO_EXEC__TESTS} \
CLANDRO_APP__NAMESPACE=${CLANDRO_APP__NAMESPACE} \
CLANDRO_APP__SHELL_API__SHELL_API_ACTIVITY__CLASS_NAME=${CLANDRO_APP__SHELL_API__SHELL_API_ACTIVITY__CLASS_NAME} \
CLANDRO_APP__SHELL_API__SHELL_API_SERVICE__CLASS_NAME=${CLANDRO_APP__SHELL_API__SHELL_API_SERVICE__CLASS_NAME} \
CLANDRO_PKGS__REPO_NAME=${CLANDRO_PKGS__REPO_NAME} CLANDRO_PKGS__REPO_URL=${CLANDRO_PKGS__REPO_URL} \
CLANDRO_PKGS__BUILD__REPO_ROOT_DIR=${CLANDRO_PKGS__BUILD__REPO_ROOT_DIR} \
CLANDRO_CORE_PKG__REPO_NAME=${CLANDRO_CORE_PKG__REPO_NAME} CLANDRO_CORE_PKG__REPO_URL=${CLANDRO_CORE_PKG__REPO_URL}"

clandro_step_install_license() {
	mkdir -p "$CLANDRO_PREFIX/share/doc/$CLANDRO_PKG_NAME/licenses"
	cp -af "$CLANDRO_PKG_SRCDIR/LICENSE" "$CLANDRO_PREFIX/share/doc/$CLANDRO_PKG_NAME/copyright"
	cp -af "$CLANDRO_PKG_SRCDIR/licenses/"* "$CLANDRO_PREFIX/share/doc/$CLANDRO_PKG_NAME/licenses/"
}

clandro_step_strip_elf_symbols() {
	clandro_step_strip_elf_symbols__from_paths . \
	\( \
		\( -path "./bin/*" -o -path "./lib/*" -o -path "./libexec/*" \) -a \
		\( ! -path "./libexec/installed-tests/clandro-core/*" \) \
	\)
}
