#!/usr/bin/env bash
# ============================================================
# proot-distro plugin: Alpine Linux XFCE (Mobile Desktop)
# Installs the pre-built Alpine XFCE rootfs for touch-friendly
# desktop environment on Android via PRoot.
# ============================================================

DISTRO_NAME="Alpine XFCE (Mobile Desktop)"
DISTRO_COMMENT="Lightweight Alpine Linux with XFCE4, VNC, and mobile-friendly UI"

# URL to download the pre-built rootfs tarball
# (generated by forge-alpine-xfce.yml CI workflow)
TARBALL_URLS=(
    "https://github.com/cl-andro/cl-andro-packages/releases/download/alpine-xfce/alpine-xfce-aarch64.tar.gz"
)

TARBALL_SHA256=(
    "0000000000000000000000000000000000000000000000000000000000000000"
)

# Override the default distro_setup to use our pre-built rootfs
distro_setup() {
    # Extract the pre-built Alpine XFCE rootfs
    run_proot_cmd /bin/true

    # If we have a local tarball, use it directly
    local tarball="${DISTRO_DIR}/alpine-xfce-aarch64.tar.gz"
    if [ -f "$tarball" ]; then
        msg "Installing Alpine XFCE from local tarball..."
        tar -xzf "$tarball" -C "$DISTRO_DIR"
        rm -f "$tarball"
        return 0
    fi

    msg "No local tarball found. Attempting download..."
    return 1
}

# Post-install: make sure services are ready
distro_post_install() {
    msg "Configuring Alpine XFCE for Android..."

    # Ensure networking works inside proot
    echo "nameserver 8.8.8.8" > "${DISTRO_DIR}/etc/resolv.conf"
    echo "nameserver 1.1.1.1" >> "${DISTRO_DIR}/etc/resolv.conf"

    # Create mount points for Android integration
    mkdir -p "${DISTRO_DIR}/sdcard"
    mkdir -p "${DISTRO_DIR}/data/data/com.zk.clandro"

    # Ensure VNC password file has correct permissions
    if [ -f "${DISTRO_DIR}/home/clandro/.vnc/passwd" ]; then
        chmod 600 "${DISTRO_DIR}/home/clandro/.vnc/passwd"
    fi

    msg "Done! Start with:  proot-distro login alpine-xfce"
    msg "Then run:          clandro-xfce"
    msg "Connect VNC to:    localhost:1"
}
