CLANDRO_PKG_HOMEPAGE=https://xorg.freedesktop.org/
CLANDRO_PKG_DESCRIPTION="Classic X utility to set your root window background to a given pattern or color"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.1.3
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://xorg.freedesktop.org/archive/individual/app/xsetroot-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=6081b45a9eb4426e045d259d1e144b32417fb635e5b96aa90647365ac96638d1
CLANDRO_PKG_DEPENDS="libx11, libxcursor, libxmu"
CLANDRO_PKG_BUILD_DEPENDS="xbitmaps, xorg-util-macros"
