CLANDRO_PKG_HOMEPAGE=http://www.openpgl.org/
CLANDRO_PKG_DESCRIPTION="Intel(R) Open Path Guiding Library"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.7.1"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://github.com/RenderKit/openpgl/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=d62d24241232a526491328f341df9add274fc84ae9818470d3edb5ae6141ac63
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++, libtbb"
# OpenPGL does not support 32-bit
CLANDRO_PKG_EXCLUDED_ARCHES="arm, i686"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DOPENPGL_BUILD_STATIC=OFF
"
