CLANDRO_PKG_HOMEPAGE=https://git.sr.ht/~sircmpwn/scdoc
CLANDRO_PKG_DESCRIPTION="Small man page generator"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="Yaksh Bariya <thunder-coding@termux.dev> & @clandro"
CLANDRO_PKG_VERSION="1.11.4"
CLANDRO_PKG_SRCURL=https://git.sr.ht/~sircmpwn/scdoc/archive/$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=e1a9c2000f855123a1a50c8f897073e0ee95fc41787431efe3864c2f1c2e7092
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="OUTDIR=$CLANDRO_PKG_SRCDIR HOST_SCDOC=$CLANDRO_PKG_HOSTBUILD_DIR/scdoc"
CLANDRO_PKG_HOSTBUILD=true

clandro_step_host_build() {
	cd $CLANDRO_PKG_SRCDIR
	make OUTDIR=$CLANDRO_PKG_HOSTBUILD_DIR
}
