CLANDRO_PKG_HOMEPAGE=https://git.zx2c4.com/music-file-organizer/about/
CLANDRO_PKG_DESCRIPTION="Organizer of audio files into directories based on metadata tags"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.0.4
CLANDRO_PKG_REVISION=10
CLANDRO_PKG_SRCURL=https://git.zx2c4.com/music-file-organizer/snapshot/music-file-organizer-$CLANDRO_PKG_VERSION.tar.xz
CLANDRO_PKG_SHA256=9e3e2df24c5293e14c40d85fb480f5d52c0dc9afac845280a356c2fb6531e43e
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_DEPENDS="libicu, taglib"
