CLANDRO_PKG_HOMEPAGE=https://lloyd.github.io/yajl/
CLANDRO_PKG_DESCRIPTION="Yet Another JSON Library"
CLANDRO_PKG_LICENSE="ISC"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=2.1.0
CLANDRO_PKG_REVISION=8
CLANDRO_PKG_SRCURL=https://github.com/lloyd/yajl/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=3fb73364a5a30efe615046d07e6db9d09fd2b41c763c5f7d3bfb121cd5c5ac5a
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_BREAKS="yajl-dev"
CLANDRO_PKG_REPLACES="yajl-dev"
CLANDRO_PKG_FORCE_CMAKE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
