CLANDRO_PKG_HOMEPAGE=https://www.cgal.org/
CLANDRO_PKG_DESCRIPTION="Computational Geometry Algorithms Library"
CLANDRO_PKG_LICENSE="GPL-3.0, LGPL-3.0, BSL-1.0, MIT"
CLANDRO_PKG_LICENSE_FILE="LICENSE, LICENSE.BSL, LICENSE.GPL, LICENSE.LGPL, LICENSE.RFL"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.1.1"
CLANDRO_PKG_SRCURL=https://github.com/CGAL/cgal/releases/download/v${CLANDRO_PKG_VERSION}/CGAL-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=52506935f70e247ed2777e3c65f20e86f79208c2a2d0e180ae7475daf11c96ef
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_GROUPS="science"

CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DWITH_CGAL_Qt5=OFF
-DWITH_demos=OFF
-DWITH_examples=OFF
-DWITH_tests=OFF
"
