CLANDRO_PKG_HOMEPAGE="https://invent.kde.org/plasma/ocean-sound-theme"
CLANDRO_PKG_DESCRIPTION="Ocean Sound Theme for Plasma"
CLANDRO_PKG_LICENSE="LGPL-2.0-or-later"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.6.4"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/plasma/${CLANDRO_PKG_VERSION}/ocean-sound-theme-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=3f6d02604eabf8ce084fa47dffa1ed1dc86728e970fd941ba058aa505348b541
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BUILD_DEPENDS="extra-cmake-modules, qt6-qtbase"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
