CLANDRO_PKG_HOMEPAGE=https://gitlab.gnome.org/GNOME/gtk-doc
CLANDRO_PKG_DESCRIPTION="GTK+ DocBook Documentation Generator"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.36.1"
CLANDRO_PKG_SRCURL=https://gitlab.gnome.org/GNOME/gtk-doc/-/archive/${CLANDRO_PKG_VERSION}/gtk-doc-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=9e5f6dd212ca2c31bd0ee804ba9672f00d30cad12c03f9aba9d15e9f74134dc4
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_DEPENDS="glib"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-Dtests=false
"
