CLANDRO_PKG_HOMEPAGE=https://libisl.sourceforge.io/
CLANDRO_PKG_DESCRIPTION="Library for manipulating sets and relations of integer points bounded by linear constraints"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.26
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://libisl.sourceforge.io/isl-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=a0b5cb06d24f9fa9e77b55fabbe9a3c94a336190345c2555f9915bb38e976504
CLANDRO_PKG_DEPENDS="libgmp"
CLANDRO_PKG_BREAKS="libisl-dev"
CLANDRO_PKG_REPLACES="libisl-dev"
