CLANDRO_PKG_HOMEPAGE="https://lexbor.com"
CLANDRO_PKG_DESCRIPTION="Fast embeddable web browser engine written in C with no dependencies"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.0.0"
CLANDRO_PKG_SRCURL="https://github.com/lexbor/lexbor/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=eafaa79ef9871f0bbb1978eda8677d184f7ecdcaa203d7cd25b3f86e32c014c2
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DLEXBOR_BUILD_SHARED=ON
-DLEXBOR_BUILD_STATIC=OFF
-DLEXBOR_BUILD_EXAMPLES=OFF
-DLEXBOR_BUILD_TESTS=OFF
-DLEXBOR_BUILD_TESTS_CPP=OFF
"
