CLANDRO_PKG_HOMEPAGE=https://orc.apache.org/
CLANDRO_PKG_DESCRIPTION="Columnar storage for Hadoop workloads"
CLANDRO_PKG_LICENSE="Apache-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.3.0"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://dlcdn.apache.org/orc/orc-${CLANDRO_PKG_VERSION}/orc-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=6c9e2f6663ac9ef34ca4ae5ae4f004a651e5fe31f2e05b6eb5d99d105091d87c
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_DEPENDS="libc++, liblz4, libprotobuf, libsnappy, zlib, zstd"
# cmake options are copied from https://github.com/apache/arrow/blob/main/cpp/cmake_modules/ThirdpartyToolchain.cmake
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_CPP_TESTS=OFF
-DBUILD_JAVA=OFF
-DBUILD_LIBHDFSPP=OFF
-DBUILD_TOOLS=OFF
-DHAS_PRE_1970_EXITCODE=0
-DHAS_POST_2038_EXITCODE=0
-DINSTALL_VENDORED_LIBS=OFF
-DORC_PREFER_STATIC_LZ4=OFF
-DORC_PREFER_STATIC_PROTOBUF=OFF
-DORC_PREFER_STATIC_SNAPPY=OFF
-DORC_PREFER_STATIC_ZLIB=OFF
-DORC_PREFER_STATIC_ZSTD=OFF
-DSTOP_BUILD_ON_WARNING=OFF
-DLZ4_HOME="${CLANDRO_PREFIX}"
-DPROTOBUF_HOME="${CLANDRO_PREFIX}"
-DSNAPPY_HOME="${CLANDRO_PREFIX}"
-DZLIB_HOME="${CLANDRO_PREFIX}"
-DZSTD_HOME="${CLANDRO_PREFIX}"
"

clandro_step_pre_configure() {
	clandro_setup_protobuf

	# Use host protoc executable
	CLANDRO_PKG_EXTRA_CONFIGURE_ARGS+=" -DProtobuf_PROTOC_EXECUTABLE=$(command -v protoc)"
	sed -i 's/COMMAND ${PROTOBUF_EXECUTABLE}/COMMAND ${Protobuf_PROTOC_EXECUTABLE}/g' ${CLANDRO_PKG_SRCDIR}/c++/src/CMakeLists.txt

	# Use shared library
	sed -i 's/orc STATIC/orc SHARED/' c++/src/CMakeLists.txt
}
