CLANDRO_PKG_HOMEPAGE=http://caca.zoy.org/wiki/toilet
CLANDRO_PKG_DESCRIPTION="FIGlet-compatible display of large colourful characters in text mode"
CLANDRO_PKG_LICENSE="WTFPL"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.3
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=http://deb.debian.org/debian/pool/main/t/toilet/toilet_${CLANDRO_PKG_VERSION}.orig.tar.gz
CLANDRO_PKG_SHA256=89d4b530c394313cc3f3a4e07a7394fa82a6091f44df44dfcd0ebcb3300a81de
CLANDRO_PKG_DEPENDS="libcaca"
CLANDRO_PKG_BUILD_IN_SRC=true
