CLANDRO_PKG_HOMEPAGE=https://www.libsdl.org
CLANDRO_PKG_DESCRIPTION="Simple DirectMedia Layer (SDL) sdl12-compat"
CLANDRO_PKG_LICENSE="ZLIB"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.2.60"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/libsdl-org/sdl12-compat/archive/refs/tags/release-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=029fa24fe9e0d6a15b94f4737a2d3ed3144c5ef920eb82b4c6b30248eb94518b
CLANDRO_PKG_DEPENDS="sdl2 | sdl2-compat"
CLANDRO_PKG_ANTI_BUILD_DEPENDS="sdl2-compat"
CLANDRO_PKG_CONFLICTS="libsdl"
CLANDRO_PKG_REPLACES="libsdl"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DSDL12TESTS=OFF
"
CLANDRO_PKG_NO_STATICSPLIT=true
