CLANDRO_PKG_HOMEPAGE=https://tomclegg.ca/mp3cat
CLANDRO_PKG_DESCRIPTION="Copies a byte stream, skipping everything except mp3 frames with valid headers"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.5
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/tomclegg/mp3cat/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=b1ec915c09c7e1c0ff48f54844db273505bc0157163bed7b2940792dca8ff951
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_CONFLICTS="mp3cat-go"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="
PREFIX=$CLANDRO_PREFIX
INSTALL_COMMAND=install
"
