CLANDRO_PKG_HOMEPAGE="https://github.com/tbeu/matio"
CLANDRO_PKG_DESCRIPTION="A C library for reading and writing Matlab MAT files"
CLANDRO_PKG_GROUPS="science"
CLANDRO_PKG_LICENSE="BSD 2-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.5.30"
CLANDRO_PKG_SRCURL="https://github.com/tbeu/matio/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=cd514c42e13bb39477e7d8fdeaa1502014c552a6a53f0678809cce6951db2bc1
CLANDRO_PKG_DEPENDS="zlib"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DMATIO_WITH_HDF5:BOOL=OFF
-DMATIO_MAT73:BOOL=OFF
-DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF
-DMATIO_SHARED:BOOL=ON
"
