CLANDRO_PKG_HOMEPAGE=https://avrdudes.github.io/avrdude/
CLANDRO_PKG_DESCRIPTION="Software for programming Microchip (former Atmel) AVR Microcontrollers"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="8.1"
CLANDRO_PKG_SRCURL=https://github.com/avrdudes/avrdude/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=2d3016edd5281ea09627c20b865e605d4f5354fe98f269ce20522a5b910ab399
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libusb"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
