CLANDRO_PKG_HOMEPAGE=https://xorg.freedesktop.org/
CLANDRO_PKG_DESCRIPTION="Utility to print information about X11 windows"
CLANDRO_PKG_LICENSE="MIT, HPND"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.1.6
CLANDRO_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/xwininfo-${CLANDRO_PKG_VERSION}.tar.xz
CLANDRO_PKG_SHA256=3518897c17448df9ba99ad6d9bb1ca0f17bc0ed7c0fd61281b34ceed29a9253f
CLANDRO_PKG_DEPENDS="libiconv, libxcb"
CLANDRO_PKG_BUILD_DEPENDS="libx11, xorg-util-macros"
