CLANDRO_PKG_HOMEPAGE=https://www.unicorn-engine.org/
CLANDRO_PKG_DESCRIPTION="Unicorn is a lightweight multi-platform, multi-architecture CPU emulator framework"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.1.4"
CLANDRO_PKG_SRCURL=https://github.com/unicorn-engine/unicorn/archive/refs/tags/$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=ea8863f095a0136388694e5a6063afd9bb7650e30243dd6251af59c5ce5601f4
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BREAKS="unicorn-dev"
CLANDRO_PKG_REPLACES="unicorn-dev"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="-DCLANDRO_ARCH=$CLANDRO_ARCH"
