CLANDRO_PKG_HOMEPAGE=https://yuriy-chumak.github.io/ol/
CLANDRO_PKG_DESCRIPTION="Purely functional dialect of Lisp"
CLANDRO_PKG_LICENSE="LGPL-3.0, MIT"
CLANDRO_PKG_MAINTAINER="Yuriy Chumak <yuriy.chumak@mail.com>"
CLANDRO_PKG_VERSION="2.7"
CLANDRO_PKG_SRCURL=https://github.com/yuriy-chumak/ol/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=32dec0d527d456cce3273b907ffface6386a61288edf33f8724e2dd1bfb22319
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_DEPENDS="xxd"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
