CLANDRO_PKG_HOMEPAGE=https://www.gnustep.org/
CLANDRO_PKG_DESCRIPTION="The GNUstep Objective-C runtime"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.3"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://github.com/gnustep/libobjc2/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=5ead2276b42a534ac40437ce53b2231320b985539dc325453d93874be8d92869
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_BUILD_DEPENDS="robin-map"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$CLANDRO__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$CLANDRO__PREFIX__INCLUDE_SUBDIR
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DENABLE_OBJCXX=OFF
-DGNUSTEP_CONFIG=OFF
-DTESTS=OFF
"

# https://github.com/gnustep/libobjc2/issues/199
CLANDRO_PKG_CONFLICTS="libblocksruntime"

clandro_step_pre_configure() {
	local target="$CCTERMUX_HOST_PLATFORM"
	if [[ "$CLANDRO_ARCH" == "arm" ]]; then
		target="armv7a-linux-androideabi$CLANDRO_PKG_API_LEVEL"
	fi
	export OBJCFLAGS="$CFLAGS --target=$target"
	export OBJCXXFLAGS="$CXXFLAGS --target=$target"
}
