CLANDRO_PKG_HOMEPAGE=https://www.gnu.org/software/gsasl
CLANDRO_PKG_DESCRIPTION="GNU SASL library"
CLANDRO_PKG_LICENSE="LGPL-2.1, GPL-3.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.2.2"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://mirrors.kernel.org/gnu/gsasl/gsasl-$CLANDRO_PKG_VERSION.tar.gz
CLANDRO_PKG_SHA256=41e8e442648eccaf6459d9ad93d4b18530b96c8eaf50e3f342532ef275eff3ba
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="libidn"
CLANDRO_PKG_BREAKS="libgsasl-dev"
CLANDRO_PKG_REPLACES="libgsasl-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
ac_cv_func_getpass=yes
--without-libgcrypt
"
