CLANDRO_PKG_HOMEPAGE=https://www.iodbc.org/
CLANDRO_PKG_DESCRIPTION="Independent Open DataBase Connectivity for Linux, MacOS X and Unix systems"
CLANDRO_PKG_LICENSE="LGPL-2.0, BSD 3-Clause"
CLANDRO_PKG_LICENSE_FILE="LICENSE, LICENSE.BSD, LICENSE.LGPL"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=3.52.16
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/openlink/iODBC/releases/download/v${CLANDRO_PKG_VERSION}/libiodbc-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=3898b32d07961360f6f2cf36db36036b719a230e476469258a80f32243e845fa
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
--disable-libodbc
--with-layout=gnu
"
