CLANDRO_PKG_HOMEPAGE=https://github.com/json-c/json-c/wiki
CLANDRO_PKG_DESCRIPTION="A JSON implementation in C"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.18"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://s3.amazonaws.com/json-c_releases/releases/json-c-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=876ab046479166b869afc6896d288183bbc0e5843f141200c677b3e8dfb11724
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BREAKS="json-c-dev"
CLANDRO_PKG_REPLACES="json-c-dev"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DDISABLE_WERROR=ON
-DHAVE_LOCALE_H=OFF
-DHAVE_XLOCALE_H=OFF
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
