CLANDRO_PKG_HOMEPAGE=https://github.com/venam/2bwm
CLANDRO_PKG_DESCRIPTION="A fast floating WM"
CLANDRO_PKG_LICENSE="ISC"
CLANDRO_PKG_LICENSE_FILE="LICENSE.2bwm, LICENSE.hidden"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.3
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/venam/2bwm/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=a4889ea4b01b1a3d4a508daa034b9d86676913cbbca1f977858df692a6e2af95
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_DEPENDS="libxcb, xcb-util-keysyms, xcb-util-wm, xcb-util-xrm"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="
PREFIX=$CLANDRO_PREFIX
X11_INCLUDE=$CLANDRO_PREFIX/include
"

clandro_step_post_get_source() {
	cp $CLANDRO_PKG_BUILDER_DIR/LICENSE.{2bwm,hidden} ./
}
