CLANDRO_PKG_HOMEPAGE=https://github.com/jamie/ciso
CLANDRO_PKG_DESCRIPTION="PSP ISO compression tool"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.0.2
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL=https://github.com/jamie/ciso/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=77a9bb615ca8918ef81f21328cb4fdc58f4cdd854cb11c16bb50a7d4d1625c09
CLANDRO_PKG_DEPENDS="zlib"
CLANDRO_PKG_BUILD_IN_SRC=true

clandro_step_make_install() {
	install -Dm700 ./"${CLANDRO_PKG_NAME}" "${CLANDRO_PREFIX}"/bin
}
