CLANDRO_PKG_HOMEPAGE=https://github.com/Ro5bert/avra
CLANDRO_PKG_DESCRIPTION="Assember for the Atmel AVR microcontroller family"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.4.2
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/Ro5bert/avra/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=cc56837be973d1a102dc6936a0b7235a1d716c0f7cd053bf77e0620577cff986
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
