CLANDRO_PKG_HOMEPAGE=https://github.com/mayTermux/awesomeshot
CLANDRO_PKG_DESCRIPTION="A command-line screenshot tool written in bash"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=1.1.0
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/mayTermux/awesomeshot/archive/refs/tags/v.${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=5daefb4c02743503e08764fb604e6a811e4ce09a301fafe7cd00a43418a687b1
CLANDRO_PKG_DEPENDS="bash, bc, imagemagick, inotify-tools, termux-api"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_AUTO_UPDATE=false
CLANDRO_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
