CLANDRO_PKG_HOMEPAGE="https://github.com/dftlibs/xcfun"
CLANDRO_PKG_DESCRIPTION="A library of exchange-correlation functionals with arbitrary-order derivatives"
CLANDRO_PKG_GROUPS="science"
CLANDRO_PKG_LICENSE="MPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.1.1"
CLANDRO_PKG_REVISION=2
CLANDRO_PKG_SRCURL="https://github.com/dftlibs/xcfun/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=8b602df74c7be83d501532565deafd1b7881946d94789122f24c309a669298ab
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DXCFUN_PYTHON_INTERFACE=OFF
-DENABLE_TESTALL=OFF
"
