CLANDRO_PKG_HOMEPAGE=http://www.catb.org/~esr/ascii/
CLANDRO_PKG_DESCRIPTION="List ASCII idiomatic names and octal/decimal code-point forms"
CLANDRO_PKG_LICENSE="BSD 2-Clause"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="3.31"
CLANDRO_PKG_SRCURL="http://www.catb.org/~esr/ascii/ascii-$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=309aa75fcc46921b3ac1bb2a6742e6e343049529ea5b4859564625be742a013c
CLANDRO_PKG_LICENSE_FILE=COPYING
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="DESTDIR=$CLANDRO_PREFIX PREFIX="
