CLANDRO_SUBPKG_INCLUDE="share/help/"
CLANDRO_SUBPKG_DESCRIPTION="GHex help files"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_BREAKS="ghex (<< 46.1)"
CLANDRO_SUBPKG_REPLACES="ghex (<< 46.1)"
