CLANDRO_PKG_HOMEPAGE="https://github.com/nelhage/reptyr"
CLANDRO_PKG_DESCRIPTION="Tool for reparenting a running program to a new terminal"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.10.0
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/nelhage/reptyr/archive/refs/tags/reptyr-${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=c6ffbc34a511ac00d072219bda30699e51f2f4eb483cbae9e32e981d49e8b380
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_METHOD=repology
CLANDRO_PKG_BUILD_DEPENDS="bash-completion"
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_EXTRA_MAKE_ARGS="PREFIX=$CLANDRO_PREFIX"
