CLANDRO_PKG_HOMEPAGE="https://github.com/tareksander/clandro-gui-pm"
CLANDRO_PKG_DESCRIPTION="A graphical package manager for various package formats for Termux and proot-distro distros"
CLANDRO_PKG_LICENSE="MPL-2.0"
CLANDRO_PKG_MAINTAINER="@tareksander"
CLANDRO_PKG_VERSION="1.0.0"
CLANDRO_PKG_REVISION=4
CLANDRO_PKG_DEPENDS="python, python-pip"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_BUILD_IN_SRC=true
CLANDRO_PKG_SRCURL="https://github.com/tareksander/clandro-gui-pm/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256="3a5a829b721d17f2002406571852e63d1984acc9732e58f2f76a2966381297c6"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_PYTHON_TARGET_DEPS="termuxgui"
