CLANDRO_SUBPKG_INCLUDE="lib/mono/"
CLANDRO_SUBPKG_DESCRIPTION="Platform-independent libraries for mono"
CLANDRO_SUBPKG_PLATFORM_INDEPENDENT=true
CLANDRO_SUBPKG_BREAKS="mono (<< 6.12.0.122-2)"
CLANDRO_SUBPKG_REPLACES="mono (<< 6.12.0.122-2)"
