CLANDRO_PKG_HOMEPAGE=https://git.vuxu.org/lr/about/
CLANDRO_PKG_DESCRIPTION="list files, recursively, includes the best features of ls, find, stat and du"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.0.1"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL="https://github.com/leahneukirchen/lr/archive/refs/tags/v$CLANDRO_PKG_VERSION.tar.gz"
CLANDRO_PKG_SHA256=c7c4a57169e1396f17a09b05b19456945c8bb5e55001c5a870b083c0b4a23cd8
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="newest-tag"
CLANDRO_PKG_BUILD_IN_SRC=true
