CLANDRO_PKG_HOMEPAGE=https://www.kde.org/
CLANDRO_PKG_DESCRIPTION="Extra CMake modules (KDE)"
CLANDRO_PKG_LICENSE="BSD 3-Clause"
CLANDRO_PKG_LICENSE_FILE="LICENSES/BSD-3-Clause.txt"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="6.26.0"
CLANDRO_PKG_SRCURL="https://download.kde.org/stable/frameworks/${CLANDRO_PKG_VERSION%.*}/extra-cmake-modules-${CLANDRO_PKG_VERSION}.tar.xz"
CLANDRO_PKG_SHA256=f4e10d9d45aafb5273e996196040f4e420f0bc4071c208282aae94d9ad8e1743
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_DEPENDS="cmake"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_HTML_DOCS=OFF
-DBUILD_QTHELP_DOCS=OFF
-DBUILD_TESTING=OFF
"
