CLANDRO_PKG_HOMEPAGE=https://github.com/zeux/volk
CLANDRO_PKG_DESCRIPTION="Meta loader for Vulkan API"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="1.4.350"
CLANDRO_PKG_SRCURL="https://github.com/zeux/volk/archive/refs/tags/${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=e47c6efe5294bb03729a976b385864bba5daf46ec60f0bdea11e1d1446345f9a
CLANDRO_PKG_BUILD_DEPENDS="vulkan-headers, vulkan-loader-generic"
CLANDRO_PKG_NO_STATICSPLIT=true
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_UPDATE_TAG_TYPE="latest-release-tag"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DVOLK_INSTALL=ON
"
