CLANDRO_PKG_HOMEPAGE=https://quickjs-ng.github.io/quickjs/
CLANDRO_PKG_DESCRIPTION="Embeddable JavaScript engine in C (NG fork)"
CLANDRO_PKG_LICENSE="MIT"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.14.0"
CLANDRO_PKG_SRCURL="https://github.com/quickjs-ng/quickjs/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=928e9406addd99eb8623348f2cfcd916eade9a263c60d42be79bc7aee4ee8453
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_CONFLICTS="quickjs"
CLANDRO_PKG_PROVIDES="quickjs"
CLANDRO_PKG_REPLACES="quickjs"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
