--- a/Makefile
+++ b/Makefile
@@ -4,9 +4,9 @@
 DESTDIR =
 
-binprefix = 
+binprefix = @CLANDRO_PREFIX@
-manprefix = /usr
+manprefix = @CLANDRO_PREFIX@
 exec_prefix = $(binprefix)/
-sbindir = $(exec_prefix)sbin
+sbindir = $(exec_prefix)bin
 mandir = $(manprefix)/share/man
 oldmandir = $(manprefix)/man
 
