CLANDRO_PKG_HOMEPAGE=https://osmcode.org/libosmium/
CLANDRO_PKG_DESCRIPTION="Library for reading from and writing to OSM files in XML and PBF formats"
CLANDRO_PKG_LICENSE="BSL-1.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="2.23.1"
CLANDRO_PKG_SRCURL="https://github.com/osmcode/libosmium/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz"
CLANDRO_PKG_SHA256=eb47d8163396c73870dbf27819dcadda0c56f0191935c4f8659d1e61b261552f
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_BUILD_DEPENDS="boost, boost-headers, liblz4, libprotozero"
CLANDRO_PKG_PLATFORM_INDEPENDENT=true
CLANDRO_PKG_GROUPS="science"
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DINSTALL_UTFCPP=ON
-DBUILD_EXAMPLES=OFF
-DBUILD_DATA_TESTS=OFF
"
