CLANDRO_PKG_HOMEPAGE=https://ninvaders.sourceforge.net
CLANDRO_PKG_DESCRIPTION="Space Invaders clone based on ncurses for ASCII output"
CLANDRO_PKG_LICENSE="GPL-2.0"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION=0.1.2
CLANDRO_PKG_REVISION=3
CLANDRO_PKG_SRCURL=https://github.com/sf-refugees/ninvaders/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=80fbdfd396efc3674c0a697e0d7c219647518cefd22e948d504bb3a677e58df3
CLANDRO_PKG_DEPENDS="ncurses"
CLANDRO_PKG_GROUPS="games"
