CLANDRO_PKG_HOMEPAGE=https://github.com/s-yata/marisa-trie
CLANDRO_PKG_DESCRIPTION="Matching Algorithm with Recursively Implemented StorAge"
CLANDRO_PKG_LICENSE="BSD 2-Clause, LGPL-2.1"
CLANDRO_PKG_LICENSE_FILE="COPYING.md"
CLANDRO_PKG_MAINTAINER="@clandro"
CLANDRO_PKG_VERSION="0.3.1"
CLANDRO_PKG_REVISION=1
CLANDRO_PKG_SRCURL=https://github.com/s-yata/marisa-trie/archive/refs/tags/v${CLANDRO_PKG_VERSION}.tar.gz
CLANDRO_PKG_SHA256=986ed5e2967435e3a3932a8c95980993ae5a196111e377721f0849cad4e807f3
CLANDRO_PKG_DEPENDS="libc++"
CLANDRO_PKG_AUTO_UPDATE=true
CLANDRO_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
